### ISSUE TITLE
No Target Alpha

### ISSUE THREAD

**Issue by Dovlek** [casualshammy/NameplateAuras#100]
Hi!

First of all, thank you for developing this wonderful addon. I'm using this addon with KuiNameplates since Kui isn't very customizable with specific auras.

However, if I'm not missing anything in the options, if I leave the alpha of the first slider on 40% the alpha is good on non targets when I have a target, but stays on 40% when I have no target.

Would it be possible to implement a no target alpha slider so when no targets are selected, my auras are 100% visible and when I target something, my auras go to 40% on non targets?

Thanks.

**Comment by casualshammy** [comment]
This option is implemented in [90002.1-beta](https://github.com/casualshammy/NameplateAuras/releases/download/90002.1-beta/NameplateAuras-90002.1-beta.zip)
