### ISSUE TITLE
Some of the auras don't seem to be tracked

### ISSUE THREAD

**Issue by void-ow** [casualshammy/NameplateAuras#102]
The only lua error I'm getting is this:
![WoWScrnShot_120820_234737](https://user-images.githubusercontent.com/38434756/101547893-0e363300-39bc-11eb-90f5-1c0bc58815e3.jpg)
and I'm not sure it's related to the issue at hand. This error happens when I try to config NA and shake my camera around a bit? Anyways, to the issue:

**Describe the bug**
Some of the auras that are supposed to be shown for enemies are not being shown. For example: Cloak of Shadows (31224), Shadow Blades (121471), Shadow Dance(185422), Aspect of the Turtle(186265), Blessing of Protection/Freedom/Sacrifice... really, the list goes on, most of the stuff is not shown. But, some auras do show: Kidney (408), Cheap Shot (1833), Cyclone (33786) ... basically, all (or most) of the CCs. This happens both when I provide a specific ID of the spell and when I just leave the name without any IDs. I think the issue is "**Show this aura during PvP only**" setting - for all the spells that I've enabled it to be "PvP-only" nothing is being shown.

Here's my profile file:
[NameplateAuras - Copy.txt](https://github.com/casualshammy/NameplateAuras/files/5662282/NameplateAuras.-.Copy.txt)
Had to rename it to txt for github to allow me to upload it.
Sidenote - this profile has pretty much everything you'd ever want to track in terms of cooldowns, I've pruned unused spells and added new ones after about 2 days of scouring wowhead, feel free to use the ids/names.

**To Reproduce**
1. Add "31224" (Cloak of Shadows) to Aura list
2. Set "enabled, show all auras" 
3. Set "show this aura on the nameplate of enemies"
4. Set "show this aura during PvP combat only" to on
5. Set aura type to "Buff"
6. Set width and height to 36
7. Duel a rogue and ask him to cloak / Go on the arena (about 80% chance you'd run into a sub anyways)
8. See that the cloak is not shown
9. Set "show this aura during PvP combat only" to off
10. Ask rogue to cloak
11. See that the cloak is shown

**Screenshots**
I've added screenshots wrapped in text, hope that's okay.

Thank you for your hard work! Hope we can resolve this issue soon!

**Comment by casualshammy** [comment]
Thanks for report!
You're right. NAuras was determining PvP state as ability to use 'Honorable Medallion' pvp talent, but now it's gone... I have to find an another way to check if player is fighting against another player.

**Comment by casualshammy** [comment]
PvP filter was replaced by "NPC and/or player" filter.
