### ISSUE TITLE
(not sure if bug) auras are overtaking every other ui element

### ISSUE THREAD

**Issue by reminiscentxd** [casualshammy/NameplateAuras#103]
![````````npa2lol](https://user-images.githubusercontent.com/76049511/102408412-61068080-3fa2-11eb-955b-c0a9f813c0b5.PNG)
![```npa](https://user-images.githubusercontent.com/76049511/102408432-6b287f00-3fa2-11eb-9b87-ccdde0b8879b.PNG)

i'm not sure if this is a bug however i'm confident this wasn't happening in BFA so maybe there's a setting i'm missing
but auras cover party/raidframes and character/target plates if the camera angle allows them to stack

any help would be massive! so sorry if this is a noob mistake on my end and there's a setting i'm missing

**Comment by casualshammy** [comment]
Hello. There is option for frame strata. Picture below is ruRU locale, but the position of controls is the same on any locale.
![1](https://user-images.githubusercontent.com/4965168/102625726-d2c70180-413d-11eb-8469-9e8a60f8eaf1.png)

**Comment by reminiscentxd** [comment]
thank you so much i appreciate it! that fixed it i feel like such a noob

been using the addon since like legion? and it randomly swapped settings im
so dumb haha

thank you!!

**Comment by casualshammy** [comment]
No, it's not your fault. When these options were added, I've changed the way auras are placed on nameplates, so icons become more "on top". It was neccessary, but caused such side effects with default settings.
