### ISSUE TITLE
Blizzard Personal Resource Display not showing up

### ISSUE THREAD

**Issue by SsokSC** [casualshammy/NameplateAuras#104]
Deselecting 'Hide Blizzard's aura frame on player' does not work all the time. It works at first and then after zoning into an arena or just going out of combat / in combat, my personal resource (Enhancement Shaman, Maelstorm proc) is hidden. Reloading UI works for the instance but problem is triggered again after leaving combat.

1) Personal Resource Bar/Spell (Maelstorm) proc works when entering combat on first reload of ui
2) Leave combat
3) Enter combat, Personal Resource Bar/Spell (Maelstorm) is no longer displayed
--
1) Reload UI
2) Repeated results outlined in 1-3 above.

**LUA Errors**
Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
Time: Fri Dec 18 17:16:46 2020
Count: 1
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:470: in function `GetPreferredInsets'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:166: in function `UpdateInsetsForType'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:150: in function `ApplyFrameOptions'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:116: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 b = 0.900000
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 background = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 0 = <userdata>
 r = 0.900000
 totalAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 g = 0.900000
 totalAbsorbOverlay = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
}

---

Message: Interface\FrameXML\AuraUtil.lua:58: Usage: local continuationToken, slot1, slot2, ... = UnitAuraSlots("unit" [, "filter"][, maxSlots][, continuationToken])
Time: Fri Dec 18 17:16:48 2020
Count: 6
Stack: Interface\FrameXML\AuraUtil.lua:58: Usage: local continuationToken, slot1, slot2, ... = UnitAuraSlots("unit" [, "filter"][, maxSlots][, continuationToken])
[string "=[C]"]: in function `UnitAuraSlots'
[string "@Interface\FrameXML\AuraUtil.lua"]:58: in function `ForEachAura'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:597: in function `UpdateBuffs'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:209: in function `OnUnitAuraUpdate'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:65: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = nil
(*temporary) = "HELPFUL|INCLUDE_NAME_PLATE_ONLY"
(*temporary) = 32
(*temporary) = nil

---

Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
Time: Fri Dec 18 17:16:47 2020
Count: 1
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:216: Usage: GetRaidTargetIndex(unit)
[string "=[C]"]: in function `GetRaidTargetIndex'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:216: in function `OnRaidTargetUpdate'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:122: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: (*temporary) = nil

**Comment by casualshammy** [comment]
This issue is fixed in [90002.3-beta](https://www.curseforge.com/wow/addons/nameplateauras/files/3144955).
