### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by knasen88** [casualshammy/NameplateAuras#106]
#### IMPORTANT! Lua errors are crucial for addressing issue! If you aren't getting any, use `/console scriptErrors 1`

**Describe the bug**
2x [ADDON_ACTION_BLOCKED] AddOn 'NameplateAuras' tried to call the protected function 'SetTargetClampingInsets()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:305: in function `SetupClassNameplateBars'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:119: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

**To Reproduce**
im not certain, but mostly happens in arenas upon entering them / they start i think.

**Screenshots**

**Comment by colmiak** [comment]
i could be wrong but i think it may be related to enemies (in arenas) starting in stealth?

**Comment by casualshammy** [comment]
I guess addon works as intended even with this error? My addon don't use 'SetTargetClampingInsets()' function, so it's tainting issue that I cannot debug without being able to reproduce it by myself...
