### ISSUE TITLE
Include pets in "show only my auras"

### ISSUE THREAD

**Issue by bardyspoon** [casualshammy/NameplateAuras#107]
I play a BM hunter, and I'd like to track Bloodshed with NameplateAuras. I want to make sure I only see my own, so I select "show only my auras." The problem with this is that I don't see the aura at all with the option selected. I'm guessing that this is because the debuff is actually being applied by my pet, and not technically me.

Would it be possible to add this as an option, or maybe even change the default behavior to include the player's pets in "show only my auras"?

**Comment by casualshammy** [comment]
Thank you for suggestion. It was implemented in version 90002.4-release.
