### ISSUE TITLE
Arena only option?

### ISSUE THREAD

**Issue by fiishscaa** [casualshammy/NameplateAuras#108]
Hello, I love this addon but was wondering if there was any way to enable it only in certain settings?

For example, I only use this addon in PvP settings so having the option to enable it in only in Arena or Battlegrounds would be a huge convenience.

**Comment by casualshammy** [comment]
Hello,
Sorry for late reply. There is per-spell option 'Show only on players'. Is it suitable for your purpose?

**Comment by ManagerWoW** [comment]
Seconding this request. A global option to make it only work on enemy players would be amazing instead of having to go through every single spell and disabling them.

**Comment by casualshammy** [comment]
Now you can select instance type as global filter.

![キャプチャ](https://user-images.githubusercontent.com/4965168/111077327-3ae07600-84e8-11eb-8922-0e77eb882e8e.PNG)
