### ISSUE TITLE
Interrupt handling has outdated code?

### ISSUE THREAD

**Issue by razko** [casualshammy/NameplateAuras#109]
Hey, so I've looked through the interrupt handling code and saw this bit:
```
-- // warlocks have 30% interrupt lockout reduction
if (UnitClassByGUID[destGUID] == "WARLOCK") then
  spellDuration = spellDuration * 0.7;
-- // Restoration Shamans and Shadow Priests have 30% interrupt lockout reduction
elseif (UnitGUIDHasAdditionalInterruptReduction[destGUID]) then
  spellDuration = spellDuration * 0.7;
end
```
Now, the way the addon determines whether a GUID is a rshaman or shadowpriest is by checking what spells they cast, until they cast something that is rshaman/sp-only, however, this table isn't updated and now includes spells that ALL priests and shamans have. Specifically it includes Mind Blast (all priests have this), Spiritwalker's Grace (elementals have this too now), Healing Stream Totem and Chain Healing (all shamans have this now):
```
addonTable.MarkerSpellsForRestorationShamansAndShadowPriests = {
	[232698] = true,	-- // Облик Тьмы
	[34914] = true,		-- // Прикосновение вампира
	[15407] = true,		-- // Пытка разума
	[47585] = true,		-- // Слияние с тьмой
	--[8092] = true,		-- // Взрыв разума
	[228260] = true,	-- // Извержение бездны
	--[79206] = true,		-- // Благосклонность предков
	[61295] = true,		-- // Быстрина
	[77130] = true,		-- // Возрождение духа
	[77472] = true,		-- // Волна исцеления
	--[5394] = true,		-- // Тотем исцеляющего потока
	--[1064] = true,		-- // Цепное исцеление
};
```
I've commented out the ones that should be ignored.

All that said, I'm not sure if these 30% reductions even exist anymore? I've tried to search a bit and I couldn't find any mention of there being a 30% reduction to interrupt duration for these specs. I've looked thru the spellbooks and googled and found nothing that mentions this. Is this some old expansion talent or set bonus effect or something? I really don't know, I haven't PvPed until recently.

There's also this part:
```
-- // pvp talents
if (UnitGUIDHasInterruptReduction[destGUID]) then
  spellDuration = spellDuration * 0.3;
end
```
from spells.lua:
```
addonTable.TalentsReducingInterruptTime = {
	[GetSpellInfo(221404)] = true, -- // Burning Determination
	[GetSpellInfo(221677)] = true, -- // Calming Waters
	[GetSpellInfo(221660)] = true, -- // Holy Concentration
};
```
I've checked these three and they no longer exist either. I guess this would never trigger either anyway so no actual effect on the addon, but still.

**Comment by casualshammy** [comment]
Hello,
Thank you for report.

> All that said, I'm not sure if these 30% reductions even exist anymore?

There were not any official patch notes, nor talents or spells even when I was writing this, but shamans and priests actually had this bonus. I'll check if it is still exists.

**Comment by casualshammy** [comment]
Thank you once more for reporting. Changes were made in version 90002.4-release.
