### ISSUE TITLE
strsplit Lua Error

### ISSUE THREAD

**Issue by wheatbread** [casualshammy/NameplateAuras#111]
#### IMPORTANT! Lua errors are crucial for addressing issue! If you aren't getting any, use `/console scriptErrors 1`

**Describe the bug**
Error:

133x NameplateAuras\src\NameplateAuras-90002.4-release.lua:1227: bad argument #2 to 'strsplit' (string expected, got nil)
[string "=[C]"]: ?
[string "@NameplateAuras\src\NameplateAuras-90002.4-release.lua"]:1227: in function `?'
[string "@NameplateAuras\src\NameplateAuras-90002.4-release.lua"]:1167: in function <NameplateAuras\src\NameplateAuras.lua:1167>

Locals:
Skipped (In Encounter)

**To Reproduce**
Not sure when it appeared in Bugsack, just noticed it after doing Torghast and some mythic 0s. 

**Screenshots**

**Comment by casualshammy** [comment]
Thank you! This bug is fixed in version 90002.5-release.

**Comment by wheatbread** [comment]
Awesome, thank you!
