### ISSUE TITLE
I cant deactivate Blizzard Buffs/Debuffs anymore

### ISSUE THREAD

**Issue by Rackelhardt** [casualshammy/NameplateAuras#113]
**Describe the bug**
title

**Screenshots**
![WoW](https://user-images.githubusercontent.com/76191859/106948457-07157200-672c-11eb-8dda-972f2fb3e1b8.jpg)

Version: NameplateAuras-90002.5-release (from today)

**Comment by hitmonone** [comment]
Same issue here. Used to be possible but option changed to "(except player)".

![image](https://user-images.githubusercontent.com/70028779/106950798-d54ddc80-6726-11eb-8ead-dacf6276de6b.png)

**Comment by respekten** [comment]
Same issue here to

**Comment by Humdibum** [comment]
yea same here

**Comment by casualshammy** [comment]
It was very stupid mistake, sorry. I've released version with fix (90002.6-release).
