### ISSUE TITLE
change the language of the game resets the spells whitelist

### ISSUE THREAD

**Issue by invizgg** [casualshammy/NameplateAuras#115]
i added a spell in the whitelist (spellid) but when i changed the game language, the spells are no longer present in the whitelist
(sorry for my pathetic english ^^)

**Comment by casualshammy** [comment]
Hello. Sorry for late reply.
Yes, it's how this addon works. No matter how you add spells (spellid, spell link, etc.), spells are stored in database by their name. Sorry.

**Comment by invizgg** [comment]
> Hello. Sorry for late reply.
> Yes, it's how this addon works. No matter how you add spells (spellid, spell link, etc.), spells are stored in database by their name. Sorry.

Np
If this isnt a bug and is functioning normally then you can close this case.
have a nice day and thank you for your reply
