### ISSUE TITLE
Frozen timer

### ISSUE THREAD

**Issue by invizgg** [casualshammy/NameplateAuras#116]
I noticed a problem on a timer which remains frozen (mm+). I feel like this timer updates when the player's camera comes back on it
I will let you watch for yourself:
https://clips.twitch.tv/MotionlessYummyUdonDeIlluminati-oX1BFIgvevegAs37

**Comment by casualshammy** [comment]
I see that timer text on video is completely broken, but I can't reproduce this bug now. May be there were any lua errors?

**Comment by invizgg** [comment]
unfortunately no
if it happens again i will try to provide more information to try to reproduce it

**Comment by invizgg** [comment]
I have new information to bring
I saw the bug again and it was on a "control" spell again ... maybe a new lead of investigation
