### ISSUE TITLE
How to see Default Blizzard Auras/Hide Nameplate?

### ISSUE THREAD

**Issue by kiramon2** [casualshammy/NameplateAuras#118]
**Is your feature request related to a problem? Please describe.**

I want to see the default blizzard Aura frames instead of the auras provided by NamePlate / other nameplate addons.

When I use KUI nameplates, if I use their auras it does not have the cooldown swipe/function like the default blizzard UI aura debuffs for self. When I use Nameplate, i see all debuffs instead of just mine. 

I know there is an option to Show blizzard frames, but it is overriden by Kui (i believe) so i do not see them. Not sure how I can enable them again. I would like primarily to use the default blizzard aura debuffs on nameplates, but cannot seem to override the KUI option. 

**Describe the solution you'd like**
Option/code to show the blizzard frames for aura debuffs or a way to disable the NamePlate auras and show the blizzard Debuff auras.

**Comment by casualshammy** [comment]
If I've understood you correctly, you want to see standard Blizzard aura frames on nameplates. If so, just uninstall NameplateAuras and then ask KUI developer about how you can disable KUI's aura frames.
