### ISSUE TITLE
Maximum number of auras

### ISSUE THREAD

**Issue by void-ow** [casualshammy/NameplateAuras#122]
**Is your feature request related to a problem? Please describe.**
Heyo, I'd like to have an option to only show a maximum number of auras. Obviously, sorting should apply, so only the specific number of the most important auras should be shown.

If this option already exists and I've missed it, I'm terribly sorry.

Thank you for your amazing addon and I hope you'd implement this suggestion, if it's not too much work. If you don't that's okay as well.

**Comment by casualshammy** [comment]
Hi,
This feature in implemented in version 90005.1-release, but without GUI option. To set the maximum number of icons per nameplate please type `/nauras max-auras N`, where `N` is number of icons. `/nauras max-auras 0` disables this feature.
