### ISSUE TITLE
Sometimes new aura doesnt get added correctly if it's over max auras number

### ISSUE THREAD

**Issue by void-ow** [casualshammy/NameplateAuras#125]
Hi, it's me again. 
Unfortunately, I've ran into a minor issue with the new max number of auras functionality.
Sometimes, when the nameplate already has a max number of auras allowed, when a new, high-priority aura is added, it is not shown:
![image](https://user-images.githubusercontent.com/38434756/113781839-f9836500-9739-11eb-9598-048a125c081f.png)

The settings for aura sorting is to sort based on icon size.
Here, warlock had Dark Soul, Rapid Contagion up on him. (sizes 35 and 34 respectively)
Then, he gets sheeped (size 36). Sheep, as expected, takes priority and gets to the top of the 3 aura queue.
After that, I fear him (size 36) (You can see that the fear is active since my nameplate addon shows the fear).

Expected: Three auras: Fear, Sheep, Dark Soul
Actual: Three auras: Sheep, Dark Soul, Rapid Contagion

Thank you for your time! Sorry if I'm being too annoying with this.

**Comment by casualshammy** [comment]
Hi,
I think that happens because sorting system doesn't know anything about icons limit. Please try using custom sorting function 
``` lua
function(aura1, aura2) return not sort_size(aura1, aura2); end
```

**Comment by void-ow** [comment]
Hey, I've tried that custom ordering thing out. Still inhibits the same behaviour - additional auras are not added to the sorting queue and are just hidden.
