### ISSUE TITLE
Icon Size When Switching Targets?

### ISSUE THREAD

**Issue by evanricard** [casualshammy/NameplateAuras#126]
Hey @casualshammy, in one-or-more enemy scenario.. could you explain why my icon size of nameplate debuffs will change whether I'm selected on a target (with debuffs) or unselecting/reselecting to another affected target with debuffs; debuff icons become enlarged upon selection of a target and will not adhere to the (ideal) size/scale I've set whereas it seems to play nice on a separate target(s) in the background. Frame strata does not appear to change but icon sizing does - I've tried overlapping and stacking nameplates.

Thank you!

Edit: additionally, also looking for information on whether I can configure nameplate debuffs globally to only show from my character - thanks a lot!

**Comment by casualshammy** [comment]
Hi,
![キャプチャ](https://user-images.githubusercontent.com/4965168/115290935-0c3f6600-a14c-11eb-89bf-77db6f2996db.PNG)

There are not batch editing currently. Unfortunately, you have to switch on `Show only my auras` option on per-spell basis. Maybe I'll add such option in the next release (if there are not conflicting filters).

**Comment by evanricard** [comment]
Right, alright not a problem! I did find the scale slider for the target but my issues is that the iconography will enlarge to a different scale if it's not the subject of my target.. I think? I will check to see if this setting is not set to 1.0

**Comment by casualshammy** [comment]
Could you please make a screenshot / gif / video of this bug? I will also appreciate if you post a screenshot of your `NameplateAuras`' settings (`Size & position` tab) + name of your nameplate addon.

**Comment by evanricard** [comment]
@casualshammy thank you expressing your interest in the problem - this very well could just be intended behavior and we're misunderstanding each other? 
[here is a video link of target dummy practice](https://www.youtube.com/watch?v=63l8QHrJq8c)

![image](https://user-images.githubusercontent.com/30779615/115430856-ba8dee80-a1d2-11eb-8a20-2d530cea633a.png)
No (other) nameplate addon is in use and I also checked my cvars for any suspicious variables I might've changed...

![image](https://user-images.githubusercontent.com/30779615/115431142-f9bc3f80-a1d2-11eb-9562-5c878d291b82.png)
size & position tab!

Thanks again @casualshammy!

**Comment by casualshammy** [comment]
Looks like it's how `Frame:SetScale` method works... I have rewrited scaling-related code and will push beta soon. Beta - because this change can potentially break everything, so I need time for testing. I'll appreciate if you'll try it out.

**Comment by evanricard** [comment]
Of course! I'll go and follow your updates for the project on curse. Thank you!

**Comment by evanricard** [comment]
I did not mean to close the issue but issue does seem to be fixed! 👍 :)
