### ISSUE TITLE
Works everywhere but Dungeons 

### ISSUE THREAD

**Issue by Nemski** [casualshammy/NameplateAuras#127]
#### IMPORTANT! Lua errors are crucial for addressing issue! If you aren't getting any, use `/console scriptErrors 1`

**Describe the bug**

**To Reproduce**

**Screenshots**

**Comment by Nemski** [comment]
As soon as i go in dungeon it does not show up on anyones nameplate but if im openworld or in pvp it will work just fine

**Comment by casualshammy** [comment]
Hi,
Are you talking about nameplates of your group members, or mobs?

**Comment by Nemski** [comment]
yeah i'm a druid healer so i wanted to see the heals over time over payers but it does not show it only shows for me in dungeons

**Comment by casualshammy** [comment]
Addons cannot modify friendly nameplates in dungeons, it is limitation from Blizzard.

**Comment by Nemski** [comment]
This is for when I click random dungeon finder and que up so does the same apply if i were to make a premade group and enter lets say a mythic dungeon through the entrance it would still be the same and not show what i set up over their names?

**Comment by casualshammy** [comment]
Don't matter how you enter dungeon or what dungeon you enter, addons can't modify friendly nameplates.
Please see link here: https://github.com/casualshammy/NameplateAuras/issues/91 (second post)

**Comment by Nemski** [comment]
That's terrible dungeons is why i wanted the add on but otherwise it works really well especially in pvp alright thanks
