### ISSUE TITLE
Frame strata - BACKGROUND

### ISSUE THREAD

**Issue by JJay1** [casualshammy/NameplateAuras#130]
Can't I put the layer priority behind the nameplate? Crowd control on multiple nameplates at the same time makes it difficult to see enemy castbars. I tried adjusting the layer of icons option in nameplateauras, but even low or background has priority over the nameplate. I'm using the ElvUI nameplate. There doesn't seem to be any relevant options in ElvUI. If so, Is there no way? Thanks again.

**Comment by casualshammy** [comment]
I'll look into it, but unfortunately there is not layer lower than `BACKGROUND`; I guess the best solution for you will be to move icons somewhere to prevent them from hiding castbars.
