### ISSUE TITLE
Hide other players' debuffs on nameplates.

### ISSUE THREAD

**Issue by ujellyx** [casualshammy/NameplateAuras#131]
I looked through the settings for several minutes now and can't seem to find an option to hide the debuffs applied by other players - is it possible to only show debuffs/buffs applied by me?
(Classic TBC)

**Comment by casualshammy** [comment]
There is per-spell option (the first checkbox in spell options window).

**Comment by ujellyx** [comment]
Thank you for the quick reply! That was it :)
