### ISSUE TITLE
Disabling on enemy nameplates

### ISSUE THREAD

**Issue by Westonmetsch** [casualshammy/NameplateAuras#132]
Let me start by saying this addon is awesome and simple.  My goal is to disable the auras on enemy nameplates.  I see the code for for showOnEnemies, but I dont see the checkbox within the addon interface.  It has everything I need but this feature!

-Wes

**Comment by casualshammy** [comment]
Hello. Sorry for late reply.
There is per-spell option (the 3rd one)
