### ISSUE TITLE
Class specific debuffs not showing up

### ISSUE THREAD

**Issue by squirfle** [casualshammy/NameplateAuras#133]
Apologies if this is a stupid question, but do I need to manually add the auras I want tracked? From what I've seen, the only auras tracked are cc spells, but it doesn't track debuffs such as rake, rip, thrash, moonfire, unless I go into the addon and add them in the spells tab.

**Comment by casualshammy** [comment]
Hello.
Yes, you have to add spells manually. The built-in list is just for... erm...example.
