### ISSUE TITLE
Option for indivdual borders for each Aura

### ISSUE THREAD

**Issue by Rackelhardt** [casualshammy/NameplateAuras#134]
First of all: "Thank You" and "great Addon". Im using it since years!

My request:
Right now i can only set animations and different glowing effects for each Aura.
But i just want individual borders.

I know there is a menu for borders but thats not very helpful for me. Also its focussing more on the debuffs and there is just one border for Buffs.

For example i want to set one border for Deff Auras (like Astral Shift or Barkskin) and one for Burst Auras (like Avenging Wrath etc.) and one for Auras i can purge (like Combustion).

If i do all that with glowings and animations my Nameplate looks like a light show. Thats just confusing.

You could set an option for individual border right below the glowing and animation option.

**Comment by casualshammy** [comment]
This feature is implemented in the latest release.

**Comment by Rackelhardt** [comment]
Thank Youuuuuu!!!

casualshammy ***@***.***> schrieb am Mi., 22. Sept. 2021,
21:12:
