### ISSUE TITLE
Display Inspiring enemy buff

### ISSUE THREAD

**Issue by mbelsky** [casualshammy/NameplateAuras#135]
Hey,

First of all I'd like to thank you for the great addon!

I've found displaying [the Explosives](https://ptr.wowhead.com/affix=13/explosive) plates in m+ very useful. What is your opinion about displaying [the Inspirings](https://ptr.wowhead.com/affix=122/inspiring) plates too by default?

**Comment by casualshammy** [comment]
Hi!
The `Explosive` icons were added because there is not any aura on orbs to determine. But `Inspiring` buff is just a... buff. You can just add it as any other regular buff or debuff.

**Comment by mbelsky** [comment]
>You can just add it as any other regular buff or debuff.

Yep and I did it for myself. I just came here with the idea to enable showing this buff out of the box because a lot of people may find it usefull.

If this idea does not match your vision for the addon please let me know.

**Comment by casualshammy** [comment]
This buff is added in the latest release (90100.15-release)
