### ISSUE TITLE
Classic SoM cant see the aura timer

### ISSUE THREAD

**Issue by Nillx** [casualshammy/NameplateAuras#141]
Im unable to see the aura timer while testing the addon on the SoM beta server. Not getting any LUA errors. It works fine in the TBC version.

**Comment by casualshammy** [comment]
Addons can't get duration of auras in Classic. It is the API restriction.

**Comment by Nillx** [comment]
I understand thanks for clarifying.

**Comment by Nillx** [comment]
Somehow ThreatPlates are able to display the timer and the spinning circle.
![Screenshot 2021-11-15 160530](https://user-images.githubusercontent.com/34476875/141795925-de99d4aa-b2f8-44e3-a03d-3212c6203d40.png)

**Comment by casualshammy** [comment]
Hmmm. Okay, I'll look into it. Restictions I've previously mentioned were active on Classic servers one (or two?) years ago, may be situation is changed now.

**Comment by Nillx** [comment]
Im not familiar what they did, from what i know Classic Era servers are running on the TBC client.

**Comment by casualshammy** [comment]
I know it's may be too late, but I've made the [initial release for Classic servers](https://www.curseforge.com/wow/addons/nameplateauras/files/3620308).
