### ISSUE TITLE
Can you update for WoW Classic Season of Mastery please? Would be awesome, thanks a lot!

### ISSUE THREAD

**Issue by maximus210793** [casualshammy/NameplateAuras#142]
Can you update for WoW Classic Season of Mastery please? Would be awesome, thanks a lot!

**Comment by casualshammy** [comment]
I've made the [initial release for Classic servers](https://www.curseforge.com/wow/addons/nameplateauras/files/3620308). I'll appreciate if you'll try it out and report about issues (I don't play on Classic servers).
