### ISSUE TITLE
Possible to make Epic Battleground's have their own visibility setting under the "General" --> "Location Visibility" Setting?

### ISSUE THREAD

**Issue by SkeenPuppy** [casualshammy/NameplateAuras#143]
Unsure if this is the right spot for this suggestion/question but I'm gonna shoot it!!!

First I want to say this addon is tremendous. It is simple, clean, and straight forward. I tried multiple Nameplate Aura addons, but this one gets the cake in my opinion. Keep up the great work!!! It is appreciated.

I know there is a Battleground option to be checked or unchecked. I usually leave this checked so I can see Aura's in 10v10 and 15v15 Battlegrounds. But when the problem of an Epic Battleground arrives, I see icons all over the screen and it not only is bothersome and unnecessary, but can cause performance spikes towards frames. Is there anyway to go about adding a new setting for Epic BG's? Or is there already one implemented I just haven't seen yet? It's not a huge deal if this isn't possible to implement or if this suggestion gets overlooked. I can always turn the addon visibility off for Battlegrounds when doing Epic's. No big deal.

As a solution, I suggest making a separate option from 10-man and 15-man Battleground's (10- and 15-man BG's can be under the same checkbox option), different than a 40v40 option. I don't know if this has been brought up before or not, so I apologize if I'm beating a dead horse. It would make frame spikes occur less. It would also make the screen a little more cleaner in Epic's.

PLEASE READ: Ideally, the option to show Aura's on target only is a fantastic addition. Very useful for this situation as well. Instead of turning battleground aura's off completely... I have resorted to using "Show Auras on Target's Nameplate Only". This makes it cleaner and more stable, as well as still getting some effect from the Addon during a 40v40. --- My question is, is there a way to make Show Auras on Target's Nameplate an option that occurs in 40v40? Like.. an option entirely for instanced visibility to show Target's Nameplate Only? If not.. how hard would it be to implement this? It's hard to explain, and probably harder to do on your end. So if you don't know what I mean or you physically can't or don't have time to do implement this... it's totally cool. Just throwing the thought!

Thanks for reading... sorry for the long paragraphs. 
Peace

**Comment by casualshammy** [comment]
> First I want to say this addon is tremendous. It is simple, clean, and straight forward. I tried multiple Nameplate Aura addons, but this one gets the cake in my opinion. Keep up the great work!!! It is appreciated.

Thank you :)
Implemented in [90105.12-release](https://github.com/casualshammy/NameplateAuras/releases/tag/90105.12-release)
