### ISSUE TITLE
Improved search keywords.

### ISSUE THREAD

**Issue by hobulian** [casualshammy/NameplateAuras#146]
Second is Improved search keywords. 
Now Nauras only has alphabetical sorting order in spell list.
Since there are tons of auras that user can add and have to handle every time
Maybe sort by icon height/width or glow type or On friendly only/enemy only. On players only/on npc only could be very helpful for recognizing and managing tons of auras that user added. Like using search key word "Width:32" or "Glow:Pixel"

Futher Hope there be presets for auras like
![image](https://user-images.githubusercontent.com/26172440/154187425-6bb4aa55-bba2-480f-a627-05444534bec9.png)
![image](https://user-images.githubusercontent.com/26172440/154187451-3f70a7aa-886e-4a27-bb0d-171210c5e158.png)

So users can easily set same sort of auras(also hope there be sorting for those presets)

**Comment by casualshammy** [comment]
Thanks for your suggestion, but this feature will not be implemented now. This feature requires a huge amount of work to reorganize database. Unfortunately, I don't have much spare time now.
