### ISSUE TITLE
Inspiring Presence size is to big

### ISSUE THREAD

**Issue by dsamlk** [casualshammy/NameplateAuras#148]
Not sure if this is supposed to be posted as a bug, but it seems to be more "feature" so here goes. 
Inspiring Presence aura is way to big and I can't find the option to change this. Would be great if this was possible.
It's the ones in the center, on the top unit you can barely see the skull marker behind it, and ofcourse this moves my nameplates further away from eachother, just making it hard to pinpoint targets during bigger pulls. 
![Inspiring-Presence](https://user-images.githubusercontent.com/102621084/160682729-85714a19-decf-488c-b12d-488ccb2f0423.png)
Since there are 3 or 4 different "category" sizes and just one alternative to change the size.
![Auras](https://user-images.githubusercontent.com/102621084/160683496-ee4ad57b-0ef9-4296-bc66-1dd704714729.png)
The size settings doesn't change this one, as it's one of the larger auras, so rezising would make the smaller ones dissapear.
I have tried to add it in the spell list and thereafter disable it, but nothing seems to be doing the trick, ofcourse it could be me who's not finding the correct setting. Any help would be great.

Thanks for a great addon, keep up the good work!

**Comment by casualshammy** [comment]
Hi!
> I have tried to add it in the spell list and thereafter disable it, but nothing seems to be doing the trick

So you have added `Inspiring` as regular aura, then disabled this feature from `Apps`. After that you still cannot change the size of regular aura, right? Seems like a bug with custom sizes...
