### ISSUE TITLE
cant resize CC buffs and cannot consistently remove auras (kevins wrath)

### ISSUE THREAD

**Issue by jaimerydev** [casualshammy/NameplateAuras#149]
i want to keep all auras the same size however some cc debuffs 2x the size of my custom sized auras. Example being mortal coil or shadowfury. Some are not though, for example capacitor totem. I can't find any way to modify this. Setting a custom size in the spell list does not seem to do anything. Additionally, trying to hide kevin's wrath to not show has no effect from spell list.

**Comment by casualshammy** [comment]
Could you please post screenshots of `General` and `Size & position` tabs in options window? Plus the screenshot of settings of aura with incorrect size.

**Comment by jaimerydev** [comment]
issue was that I was showing debuffs applied by player always while expecting to be able to hide some of them. Perhaps this would be good future feature. For now I've just manually audited the spell list while disabling that feature.
