### ISSUE TITLE
Auras not working in dungeons/raids

### ISSUE THREAD

**Issue by Sefforia** [casualshammy/NameplateAuras#151]
This might be user error, but all the sudden my healing auras on friendly nameplates (to track my renew, prayer of mending, guardian spirit) haven't been working in dungeons or raids, though my damaging auras on enemies (shadow word pain and holy fire) along with the dispel aura for friendly ARE WORKING in dungeons/raids. Everything works fine in pvp groups and open world situations. I haven't changed anything, and a week ago when I was doing timewalking the friendly healing auras were working fine. I made sure I have 5man dungeons enabled and have just spent 2 hours testing out ways to get them to work in dungeons again, to no avail. I am very dependent on this addon because I don't like using anything other than the blizzard nameplates, and this addon allows me to do that and still track my spells. I would love some help fixing this, if I am the one who caused it, idk if it's just a glitch or what. I need HELP!! Please, I am desperate, I love this addon.

**Comment by casualshammy** [comment]
Hello. Sorry for the late answer.
Please read this: https://github.com/casualshammy/NameplateAuras/issues/91

**Comment by Sefforia** [comment]
Damn that's unfortunate. I didn't know me being able to see my renew on
targets properly was that game breaking. lol Thanks Blizzard.

Tysm for responding
