### ISSUE TITLE
Bug with soulglow spectrometer

### ISSUE THREAD

**Issue by Munafsd** [casualshammy/NameplateAuras#154]
Tried to remove soulglow spectrometer from buffs and tried changing the size of the buff instead it multiplied the buff and size stayed the same. Current settings on the buff spell id have been disabled same with similar auras with the name. Same thing happened with slaughterhouse but it fixed itself after a reload.

**Comment by casualshammy** [comment]
Please post the output of `/nauras debug` command

**Comment by Munafsd** [comment]
Message: ...terface\AddOns\NameplateAuras\src\NameplateAuras.lua:376: table index is nil
Time: Wed Jul  6 11:42:20 2022
Count: 2
Stack: ...terface\AddOns\NameplateAuras\src\NameplateAuras.lua:376: table index is nil
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: ?
[string "@Interface\AddOns\NameplateAuras\src\NameplateAuras.lua"]:376: in function `RebuildSpellCache'
[string "@Interface\AddOns\NameplateAuras\src\options-dialog.lua"]:1803: in function <...terface\AddOns\NameplateAuras\src\options-dialog.lua:1757>
[string "=[C]"]: in function `Click'
[string "@Interface\AddOns\NameplateAuras\src\options-dialog.lua"]:1728: in function <...terface\AddOns\NameplateAuras\src\options-dialog.lua:1728>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
Message: ...terface\AddOns\NameplateAuras\src\NameplateAuras.lua:376: table index is nil
Time: Wed Jul  6 11:42:57 2022
Count: 10
Stack: ...terface\AddOns\NameplateAuras\src\NameplateAuras.lua:376: table index is nil
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: ?
[string "@Interface\AddOns\NameplateAuras\src\NameplateAuras.lua"]:376: in function `RebuildSpellCache'
[string "@Interface\AddOns\NameplateAuras\src\options-dialog.lua"]:1778: in function <...terface\AddOns\NameplateAuras\src\options-dialog.lua:1757>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
Message: ...terface\AddOns\NameplateAuras\src\options-dialog.lua:1526: bad argument #1 to 'next' (table expected, got nil)
Time: Wed Jul  6 11:43:02 2022
Count: 3
Stack: ...terface\AddOns\NameplateAuras\src\options-dialog.lua:1526: bad argument #1 to 'next' (table expected, got nil)
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: ?
[string "=[C]"]: in function `next'
[string "@Interface\AddOns\NameplateAuras\src\options-dialog.lua"]:1526: in function <...terface\AddOns\NameplateAuras\src\options-dialog.lua:1520>
[string "@Interface\AddOns\NameplateAuras\src\options-dialog.lua"]:1961: in function <...terface\AddOns\NameplateAuras\src\options-dialog.lua:1957>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
Message: ...terface\AddOns\NameplateAuras\src\NameplateAuras.lua:376: table index is nil
Time: Wed Jul  6 11:42:55 2022
Count: 1
Stack: ...terface\AddOns\NameplateAuras\src\NameplateAuras.lua:376: table index is nil
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: ?
[string "@Interface\AddOns\NameplateAuras\src\NameplateAuras.lua"]:376: in function `RebuildSpellCache'
[string "@Interface\AddOns\NameplateAuras\src\options-dialog.lua"]:1778: in function <...terface\AddOns\NameplateAuras\src\options-dialog.lua:1757>
[string "=[C]"]: in function `Click'
[string "@Interface\AddOns\NameplateAuras\src\options-dialog.lua"]:1728: in function <...terface\AddOns\NameplateAuras\src\options-dialog.lua:1728>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
Message: ...terface\AddOns\NameplateAuras\src\NameplateAuras.lua:117: bad argument #2 to 'string_format' (string expected, got nil)
Time: Wed Jul  6 11:44:56 2022
Count: 2
Stack: ...terface\AddOns\NameplateAuras\src\NameplateAuras.lua:117: bad argument #2 to 'string_format' (string expected, got nil)
[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\NameplateAuras\src\NameplateAuras.lua"]:117: in function <...terface\AddOns\NameplateAuras\src\NameplateAuras.lua:87>
[string "@Interface\AddOns\NameplateAuras\src\NameplateAuras.lua"]:266: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5188: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4852: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4888: in function <Interface\FrameXML\ChatFrame.lua:4884>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
