### ISSUE TITLE
Always show own auras, except when they are disabled on purpose

### ISSUE THREAD

**Issue by Ch40zz** [casualshammy/NameplateAuras#157]
I generally want to see all of my self-casted auras, without the need to manually add all of them to the spell list. 
However, for a few auras that are on a target 24/7 (e.g. `Shadow Embrace`) I'd really like to hide them to save the screen space for more useful auras/information.

I really like the `Always show own auras` feature, however I'd like to hide 1 or 2 auras, although they were casted by me.
I'm not sure what the best way to implement would be, maybe a second  checkbox in misc tab or maybe an override checkbox in the specific spell. 

Thanks a lot for your work on this addon <3

**Comment by casualshammy** [comment]
Hello! Blacklist is added in [90207.1-release](https://www.curseforge.com/wow/addons/nameplateauras/files/3945020)
![image](https://user-images.githubusercontent.com/4965168/185791139-e5c4cbc0-f950-4af4-afcc-64cb5d3886ea.png)

**Comment by Ch40zz** [comment]
Awesome, thanks a lot for adding this so quickly, works perfectly :)
Feel free to close the issue when you are satisfied with the feature!
