### ISSUE TITLE
Aura Option "Only cast by me"

### ISSUE THREAD

**Issue by aleksander-dorcov-94** [casualshammy/NameplateAuras#158]
**Is your feature request related to a problem? Please describe.**
When ever we create a new aura to have to the option "Only cast by me". When ever I want to track moonfire/sunfire for an example it shows the auras of other druids as well, and this is not helpfull at all.

If you could add another checkbox here that says "Only cast by me"  it will be awesome. Ty.
[Screenshot](https://ibb.co/Q8FCmV8)

**Comment by casualshammy** [comment]
Hi! This is not very obvious, but this feature is here ->>
![image](https://user-images.githubusercontent.com/4965168/188270122-31c6932f-c08f-4297-ab45-bb5286132272.png)

**Comment by PatriQ94** [comment]
It'd be very nice to have by default this enabled to "show only _my_ auras" on all spells or at least an option, where it automatically disables/hides other players debuffs (non "my" auras").

For example if you have few locks in a group, its literary impossible to track dots above the targets, therefore such feature would be very welcome. If I remember correctly PlateBuffs and flyPlateBufffs have done this out of the box.
