### ISSUE TITLE
Can you update for wotlkc please?

### ISSUE THREAD

**Issue by crynolf** [casualshammy/NameplateAuras#159]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by casualshammy** [comment]
There is beta for WotLK: https://github.com/casualshammy/NameplateAuras/releases/download/30400.1-beta/NameplateAuras-30400.1-beta.zip
WAGO: https://addons.wago.io/addons/nameplateauras/versions?stability=beta
CurseForge rejects my file due to strange error in their packager

**Comment by crynolf** [comment]
great thanks
