### ISSUE TITLE
Can you add blacklist for specific units?

### ISSUE THREAD

**Issue by hobulian** [casualshammy/NameplateAuras#160]
In fated raid when chaotic essence and chaotic mots came out there's tons of lag.

Hope I can add this mobs to blacklist and auras are not to be shown on their nameplates.

**Comment by casualshammy** [comment]
Hello!
I know it's a bit late 😅, but... implemented in [90207.7-release](https://github.com/casualshammy/NameplateAuras/releases/tag/90207.7-release)
![image](https://user-images.githubusercontent.com/4965168/196059454-d15b5929-37db-4b15-8de9-d633f8b86b79.png)
