### ISSUE TITLE
NameplateAuras-90207.3-release

### ISSUE THREAD

**Issue by DakJaniels** [casualshammy/NameplateAuras#161]
Retail

5x NameplateAuras\locales\itIT.lua:5: unexpected symbol near '<'

Locals:

**Screenshots**

![nameplateauraerror](https://user-images.githubusercontent.com/107732615/192166791-c108e2da-93a2-4cb1-b75c-3354bb002c5b.png)

**Comment by casualshammy** [comment]
Thanks for reporting, fixed in 90207.4-release

**Comment by DakJaniels** [comment]
Awesome. Thank you.
