### ISSUE TITLE
Default Aura Mouseover Style

### ISSUE THREAD

**Issue by Qwertdd** [casualshammy/NameplateAuras#162]
I'm a big fan of WoW's default style/theming. NameplateAuras generally respects that, but for the [General > "Show aura name when mouse is over auras icon"] option, Nauras uses a custom mouseover tooltip. Could a sub-checkbox be added that allows mouseover tooltips to be WoW's base, unedited style?

![DefaultMouseover](https://user-images.githubusercontent.com/114839012/193432713-183e2d03-1d23-4a2b-96e9-aa92d89756d7.png)

![NAurasMouseover](https://user-images.githubusercontent.com/114839012/193432716-0ee6e289-5aeb-42cb-a35e-631e0d812331.png)

**Comment by casualshammy** [comment]
Hello.
Implemented in 90207.6-release
![image](https://user-images.githubusercontent.com/4965168/194720785-5059fee7-dd9f-414f-b469-fa669cd64c07.png)

**Comment by Qwertdd** [comment]
Thanks so much!
