### ISSUE TITLE
Debuffs wont show on target name plate 

### ISSUE THREAD

**Issue by Diddyliviu** [casualshammy/NameplateAuras#164]
Hello , i use the script error and the addon still wont work

So i have installed the addon NamePlateAuras and at first it worked fine , after i tunned it a bit and wanted to test it. In Test mode everything was all right but when i close Test mode to see if the debuffs are shown on the target name plates it just wont work.
Tried to uninstall the addon and reinstall it again 
I think it must be something with the game registry that was messed up since it worked before 
Added screenshots to see whats going on 
![Normal Mode](https://user-images.githubusercontent.com/116359175/197254793-8f252635-2338-4283-a6b9-6db150338821.jpg)
![Test Mode](https://user-images.githubusercontent.com/116359175/197254798-3290193a-dd47-4024-b632-d3f3ce73892b.jpg)
Is there anything i can do to reset the games settings regarding the nameplates or something ?

Thank you !

**Comment by casualshammy** [comment]
Hello.

To delete NameplateAuras settings for classic WoW you should delete these two files:
```<World of Warcraft folder>\_classic_\WTF\Account\<account id>\SavedVariables\NameplateAuras.lua```
```<World of Warcraft folder>\_classic_\WTF\Account\<account id>\SavedVariables\NameplateAuras.lua.bak```
