### ISSUE TITLE
Spells list Size

### ISSUE THREAD

**Issue by nylathak** [casualshammy/NameplateAuras#166]
This is the main reason why I don't swap from FlyPlateBuffs even tho its not updated. If you guys could make the spells you add to the list have specific Size, and by that i dont mean Icon width or Icon height, because modifying the 2 numbers for every specific spell you add its too annoying 

I would like so it has a Size or Scale option in every spell so its easier
Also could be like this, instead of that you save specific size for specific categories like:
Stuns: 1.2
Fears: 1.4
Enemy offensives: 1.5
Enemy defensives: 1.5
Would be a nice idea so people could quickly select the size of newly created spells.

**Comment by casualshammy** [comment]
Sorry, there are no plans for implementing categories now.
As for "scale", well, users are free to use addons as they like, but I guess sizing spells is not often done. So, there are no plans to implement two different size options: `height-width` and `scale`. Sorry.
