### ISSUE TITLE
100002.3-release bug report - "Hide Blizzard's aura frames on player" and "Hide Blizzard's aura frames (except player)"

### ISSUE THREAD

**Issue by sdaynight** [casualshammy/NameplateAuras#170]
Turned on option "Hide Blizzard's aura frames on player" and "Hide Blizzard's aura frames (except player)"

but they appear and disappear for a while when i change my target.

Coudn't find this issue on 100002.2-release version.

![circled](https://user-images.githubusercontent.com/121011852/208384467-ade9b223-6d34-4a2f-a6ae-2dc2952ec9ec.jpg)

**Comment by sdaynight** [comment]
missclicked button :-(

issue still exists

Debuffs in the upper circle dont disappear until they end. My buffs in the bottom circle appear briefly and then disappear

**Comment by Humdibum** [comment]
I have the same problem since the last update.

**Comment by casualshammy** [comment]
Could you please check the version `100002.5-release`?

**Comment by RaefWolfe** [comment]
I am still seeing blizzard's default aura information even after the update on Dec 20. This issue did not exist in the Dec 11 update and I have to keep going back to it to resolve the issue.

**Comment by sdaynight** [comment]
Tested 100002.5-release version

Debuffs in the upper circle appearing from the start of the battle now, they remain until they end.

My buffs in the bottom circle appear after i change my target, but they are not appear briefly and then disappear now. They displayed continuously

Finish the combat and tested again, it was in the same condition as the first time.
Debuffs in the upper circle appearing from the start of the battle, my buffs in the bottom circle appear after i change my target

**Comment by sdaynight** [comment]
Tested 100002.6-release version

These options seems to be working well! Debuffs, my buffs neither of them appears anymore.

Thank you for your quick response !

**Comment by neuvo123** [comment]
it is still hideing buffs on players personal resource display

i have to do reload time to time to get them show again

i think something is overlaping with somehting i dont get any lua error for it so i cant know what
