### ISSUE TITLE
Auras not showing up in dungeon

### ISSUE THREAD

**Issue by Dorrjee** [casualshammy/NameplateAuras#171]
Hi there

This is probably just me not selecting the right options, but I am unable to get my  HoTs to show up like those in my screenshot in a five-man dungeon.  They appear correctly outside of a group or even in Battlegrounds, but not in a dungeon it seems - they just don't show up at all.  Is there something I am missing?

Many thanks in advance!

![Screenshot 2022-12-23 134820](https://user-images.githubusercontent.com/121299970/209346421-59fd3e75-55c9-4f37-898f-29a616e1388d.png)

![2](https://user-images.githubusercontent.com/121299970/209346908-7f104e92-f1ab-40e3-955a-46e1a11597eb.jpg)

**Comment by casualshammy** [comment]
Hi,
Please read this: https://github.com/casualshammy/NameplateAuras/issues/91

**Comment by Dorrjee** [comment]
> Hi, Please read this: #91

Thank you for your prompt reply.  Well, that explains it, cheers!
