### ISSUE TITLE
Feature Request: Healer Mark for Arena

### ISSUE THREAD

**Issue by Rackelhardt** [casualshammy/NameplateAuras#172]
Hey... since Ranked Solo Shuffle is a thing i have problems tracking my healer so i dont l.o.s. him.
I know they have that tiny diamond mark but thats way too small.
Is it possible to give us the chance to track our Healer via an icon where we can change the size on our own. Like a red Medical red Cross or something like that.
I know that other addons can detect Healer specc automatically.

I just need a huge red cross above my healer!!! xD

**Comment by casualshammy** [comment]
Hi!
Sorry, this feature is beyond the purpose of my addon. Have you tried [HHTD](https://www.curseforge.com/wow/addons/h-h-t-d)?
