### ISSUE TITLE
Flash Animation

### ISSUE THREAD

**Issue by Mixoz** [casualshammy/NameplateAuras#173]
I saw an older Ticket marked completed where someone was asking about a Flash animation when a debuff is close to expiring, is it yet implemented in the game and if no is it going to be soon added?

**Comment by casualshammy** [comment]
Hello,
Flash animation is implemented
![image](https://user-images.githubusercontent.com/4965168/211063839-97889536-16d0-4fce-8f61-2a0bf9331108.png)
