### ISSUE TITLE
"Hide Blizzard's aura frames (except player)" hides player buffs on personal resource display

### ISSUE THREAD

**Issue by neuvo123** [casualshammy/NameplateAuras#174]
I dont gain any lua error for it and doing a simple reload when i notice it seems to get the buffs back showing on personal resource display

buffs like evasion, shadow dance, cloak etc everything that normally show on the personal resource display under ur character

now after this addon update i think something is interfering with it as they keep disappearing

sorry that i cannot provide lua error for this bug sadly

**Comment by casualshammy** [comment]
Hi,
Please try out the latest release (`100002.8-release`)

**Comment by neuvo123** [comment]
Can confirm they show now, thank u
