### ISSUE TITLE
Icons need to be cute.

### ISSUE THREAD

**Issue by eduphil** [casualshammy/NameplateAuras#176]
**Is your feature request related to a problem? Please describe.**
Icons don't look cute.

**Describe the solution you'd like**
Please add support for the addon 'masque' to enable users to chose from a variety of designs for icons in order to make icons cute.

**Comment by casualshammy** [comment]
Hello.
Masque support will not be implemented until Masque becomes to be able to decorate `Frames`, not only `Buttons`. I have already tried to implement it: 
https://github.com/casualshammy/NameplateAuras/issues/67#issuecomment-698497971 
https://github.com/casualshammy/NameplateAuras/issues/67#issuecomment-703159671

But, if you really want cute icons, I suggest using the `custom border texture` feature from the `Icon borders` tab of the settings window. Pay attention that your masque border texture may be incompatible with this feature.

**Comment by eduphil** [comment]
Ty for the reply, sad to hear. My favored shaped borders like circles and hexagons don't work though :(

**Comment by casualshammy** [comment]
I have managed to add experimental Masque support in the latest release (100002.20-release).

**Comment by eduphil** [comment]
Nice!
