### ISSUE TITLE
OmniCC support appears to be disabled

### ISSUE THREAD

**Issue by urog** [casualshammy/NameplateAuras#177]
Hi there,

I just started using this. Great addon!

I noticed in your changelog that you've added support for OmniCC: https://github.com/casualshammy/NameplateAuras/blob/0e62f9341e0b1ddffc92e048a677557761939ed0/CHANGELOG.html#L1085 but have also found some curious config in the source https://github.com/casualshammy/NameplateAuras/blob/0e62f9341e0b1ddffc92e048a677557761939ed0/src/NameplateAuras.lua#L700 that appears to disable support for it. I've also noticed that the icon/timer frames are anonymous, so any special treatment in OmniCC won't work. If I switch `icon.cooldownFrame.noCooldownCount` to `false` - I am able to use OmniCC with this addon.

Is there something I'm missing to get these addons to work together? Or is this something you can quickly fix?

Thanks!

**Comment by casualshammy** [comment]
Hi!

I don't remember why, but OmniCC support was disabled by intent. Maybe OmniCC was unstable, or some compatibility error... For now, seems like OmniCC works flawlessly if the `noCooldownCount` property's value is `false`...
However, I have no plans for returning OmniCC support back now, but I will appreciate your feedback if you feel like built-in cooldown numbers are not as customizable as they can be.

**Comment by urog** [comment]
The built-in timers are fine, it's just that I've gone to some effort to setup rules/groups to theme various timers in my UI. Thanks for your quick reply.
