### ISSUE TITLE
Phase 2 Classic WoTLK problems

### ISSUE THREAD

**Issue by Zixme** [casualshammy/NameplateAuras#178]
Hello,

Maybe this issue is already being worked out but the new phase 2 patch on Classic WotlK has made the addon not work correctly anymore.

Weirdly it seems to especially get confused/broken when a nameplate has some aura that a user has set to appear on debuff made by player with the purge aura's enable, when one enemy buffs himself with a purge-able spell, the debuff aura set by the player disapear from the nameplate and get replaced by the purge aura.

I don't know, it's probably the classic new phase that breaks a lot of addons anyway haha.

**Comment by casualshammy** [comment]
Hello,
Firstly, I'm not playing Classic, so I test my addon on fresh DK, and I need detailed explanation of bug. Unfortunately, I can't clearly understand the case described in your report. Could you please make a list of actions to reproduce bug? Smth like
1. have purgable aura on enemy
2. have aura with the same name in NAuras's spell list
3. ...

I'll release updated NAuras WotLK version now (30401.2-release), please check it out.

**Comment by Zixme** [comment]
It seems to have gotten fixed, can't reproduce it.
