### ISSUE TITLE
Needs updating please WOTLK

### ISSUE THREAD

**Issue by beefybear** [casualshammy/NameplateAuras#179]
Hi! Thanks once again for this amazing addon. I was hoping we could get an update for the most recent ulduar patch. The icons constantly disappear and unable to add or remove anything. Thanks!

**Comment by casualshammy** [comment]
Please try the latest WotLK release: [30401.2-release](https://github.com/casualshammy/NameplateAuras/releases/tag/30401.2-release)
#178
