### ISSUE TITLE
LibCustomGlow Error.

### ISSUE THREAD

**Issue by Agrias2** [casualshammy/NameplateAuras#181]
I keep getting this error spam during combat with other players around. Any idea what might be the problem and how to fix it?

36x ...eplateAuras/libs/LibCustomGlow/LibCustomGlow-1.0-15.lua:48: Usage: self:RemoveMaskTexture(mask)
[string "=[C]"]: in function `RemoveMaskTexture'
[string "@Interface/AddOns/NameplateAuras/libs/LibCustomGlow/LibCustomGlow-1.0-15.lua"]:48: in function `resetterFunc'
[string "@Interface/SharedXML/Pools.lua"]:52: in function `Acquire'
[string "@Interface/AddOns/NameplateAuras/libs/LibCustomGlow/LibCustomGlow-1.0-15.lua"]:107: in function <...eplateAuras/libs/LibCustomGlow/LibCustomGlow-1.0.lua:87>
[string "@Interface/AddOns/NameplateAuras/libs/LibCustomGlow/LibCustomGlow-1.0-15.lua"]:380: in function `AutoCastGlow_Start'
[string "@Interface/AddOns/NameplateAuras/src/NameplateAuras.lua"]:1062: in function `?'
[string "@Interface/AddOns/NameplateAuras/src/NameplateAuras.lua"]:1140: in function <...terface/AddOns/NameplateAuras/src/NameplateAuras.lua:1128>
[string "@Interface/AddOns/NameplateAuras/src/NameplateAuras.lua"]:1240: in function <...terface/AddOns/NameplateAuras/src/NameplateAuras.lua:1205>
[string "@Interface/AddOns/NameplateAuras/src/NameplateAuras.lua"]:1006: in function <...terface/AddOns/NameplateAuras/src/NameplateAuras.lua:966>
[string "@Interface/AddOns/NameplateAuras/src/NameplateAuras.lua"]:1416: in function `?'
[string "@Interface/AddOns/NameplateAuras/src/NameplateAuras.lua"]:1298: in function <...terface/AddOns/NameplateAuras/src/NameplateAuras.lua:1298>

Locals:
(*temporary) = Texture {
 0 = <userdata>
}
(*temporary) = nil

**Comment by casualshammy** [comment]
I'm not sure how to reproduce this bug. Could you please describe how to get this error?

**Comment by Agrias2** [comment]
Hmm so it's just me. I'll try to disable all my addons except this one and test a bit more then share my settings and info when I have a moment.

**Comment by Agrias2** [comment]
OK i managed to replicate this bug on my alt.
Added "Avenging Wrath" spell to enemy nameplates then I used for it: Show glow all the time > Glow type: Auto-use button.
With this glow and some of the other as well it never shows icon above the nameplate just spams errors in my bug grabber addon.

**Comment by Agrias2** [comment]
I deleted half of the spells from the default list that I didn't need and it seems to be fine now. I haven't seen errors for a while now, so it's probably one or more spells from the default list caused this errors.

**Comment by casualshammy** [comment]
I'm sorry for the late reply, and I appreciate your help. This bug is fixed in `100002.15-release`
