### ISSUE TITLE
100002.13-release on retail alot lua error

### ISSUE THREAD

**Issue by neuvo123** [casualshammy/NameplateAuras#182]
Blasted by this error through rbg not sure what is causing it

Only thing i could see when im hearing it were not able see my own Purge the Wicked on target while there was another priest in party

Ive set the spell as "Enable, only show my auras" everything seems to be in order but i noticed sometimes it wouldnt show on the nameplates and i were thinking if the another discs spell disrupts it

This all i could think of but im not sure if it is related, Im sorry

This is the error I was blasted by 99 times row during one rbg

99x NameplateAuras/src/NameplateAuras.lua:82: attempt to index local '_unitAuraInfo' (a nil value)
[string "@NameplateAuras/src/NameplateAuras.lua"]:82: in function `func'
[string "@FrameXML/AuraUtil.lua"]:46: in function <FrameXML/AuraUtil.lua:38>
[string "@FrameXML/AuraUtil.lua"]:65: in function <FrameXML/AuraUtil.lua:58>
[string "@NameplateAuras/src/NameplateAuras.lua"]:96: in function <NameplateAuras/src/NameplateAuras.lua:85>
[string "@NameplateAuras/src/NameplateAuras.lua"]:1516: in function `?'
[string "@NameplateAuras/src/NameplateAuras.lua"]:1432: in function <NameplateAuras/src/NameplateAuras.lua:1432>

Locals:
_unitAuraInfo = nil
(*temporary) = <table> {
 106316 = <table> {
 }
 106937 = <table> {
 }
 106205 = <table> {
 }
}
(*temporary) = "Player-1305-0C2DF086"
(*temporary) = "attempt to index local '_unitAuraInfo' (a nil value)"
PlayerAurasPerGuid = <table> {
 Player-581-0A186A76 = <table> {
 }
 Creature-0-4253-2444-371-197833-0000634167 = <table> {
 }
 Player-1416-09985E8E = <table> {
 }
 Creature-0-4253-2444-371-189632-0000634168 = <table> {
 }
 Player-3703-0559B681 = <table> {
 }
 Player-1416-0A697CDF = <table> {
 }
 Creature-0-4253-2444-371-198594-0001634168 = <table> {
 }
 Creature-0-4253-2444-371-198594-0000634168 = <table> {
 }
 Creature-0-4253-2444-371-189617-0000634167 = <table> {
 }
 Player-1416-0A524751 = <table> {
 }
 Creature-0-4253-2444-371-194649-0000634168 = <table> {
 }
 Creature-0-4253-2444-371-194644-0000634167 = <table> {
 }
 Player-3686-044D4612 = <table> {
 }
 Player-1305-0C2DF086 = <table> {
 }
 Player-1416-0993ABBE = <table> {
 }
 Player-3391-0C1922A3 = <table> {
 }
 Player-1597-06BE6CF7 = <table> {
 }
 Player-580-0A59F56D = <table> {
 }
 Creature-0-4253-2444-371-194648-0000634167 = <table> {
 }
 Player-1416-09D062A0 = <table> {
 }
 Player-1401-0176CDE3 = <table> {
 }
 Player-1402-0A60E2BB = <table> {
 }
 Player-1379-084F1FA4 = <table> {
 }
 Player-1105-0605F932 = <table> {
 }
 Player-1301-0C2DCDAF = <table> {
 }
 Player-3391-0C53F632 = <table> {
 }
 Player-1329-09C0E61F = <table> {
 }
 Player-612-057B8784 = <table> {
 }
 Creature-0-4253-2444-371-198594-0001E34168 = <table> {
 }
 Creature-0-4253-2444-371-198594-0000E34168 = <table> {
 }
 Player-1303-0BCB4E2B = <table> {
 }
 Player-1416-08E32EE1 = <table> {
 }
 Creature-0-4253-2444-371-194643-0000634167 = <table> {
 }
 Player-1329-09CFF970 = <table> {
 }
 Creature-0-4253-2444-371-198594-0002634168 = <table> {
 }
}
p_updateAurasCurrentUnit = "Player-1305-0C2DF086"

**Comment by casualshammy** [comment]
Thank you for detailed report, I really appreciate it.
Looks like you have found bug in Blizzard code I have not taken into consideration 😅
I have pushed version `100002.14-release`, hope it helps

**Comment by neuvo123** [comment]
210x NameplateAuras/src/NameplateAuras.lua:82: attempt to index local '_unitAuraInfo' (a nil value)
[string "@NameplateAuras/src/NameplateAuras.lua"]:82: in function `func'
[string "@FrameXML/AuraUtil.lua"]:46: in function <FrameXML/AuraUtil.lua:38>
[string "@FrameXML/AuraUtil.lua"]:65: in function <FrameXML/AuraUtil.lua:58>
[string "@NameplateAuras/src/NameplateAuras.lua"]:96: in function <NameplateAuras/src/NameplateAuras.lua:85>
[string "@NameplateAuras/src/NameplateAuras.lua"]:1516: in function `?'
[string "@NameplateAuras/src/NameplateAuras.lua"]:1432: in function <NameplateAuras/src/NameplateAuras.lua:1432>

Locals:
_unitAuraInfo = nil
(*temporary) = <table> {
 543785 = <table> {
 }
 544169 = <table> {
 }
 543676 = <table> {
 }
 542199 = <table> {
 }
 543047 = <table> {
 }
 544120 = <table> {
 }
 546864 = <table> {
 }
 544084 = <table> {
 }
 545934 = <table> {
 }
}
(*temporary) = "Player-1621-0790FF50"
(*temporary) = "attempt to index local '_unitAuraInfo' (a nil value)"
PlayerAurasPerGuid = <table> {
 Creature-0-4254-2444-16430-189632-00006613AA = <table> {
 }
 Creature-0-4254-2444-16430-194643-00006613AA = <table> {
 }
 Creature-0-4254-2444-16430-194644-00006613AB = <table> {
 }
 Creature-0-4248-2444-4677-198594-0001E6271F = <table> {
 }
 Creature-0-4254-2444-16430-197833-00006613AA = <table> {
 }
 Creature-0-4254-2444-16430-198594-0001E613AA = <table> {
 }
 Player-1390-0C58082B = <table> {
 }
 Creature-0-4248-2444-4677-194643-000066271F = <table> {
 }
 Creature-0-4254-2444-16430-194648-00006613AA = <table> {
 }
 Player-1315-0C1FD5A7 = <table> {
 }
 Player-1390-0C4C8AAA = <table> {
 }
 Creature-0-4248-2444-4677-189617-000066271F = <table> {
 }
 Player-1621-0790FF50 = <table> {
 }
 Creature-0-4248-2444-4677-194648-0000662720 = <table> {
 }
 Creature-0-4248-2444-4677-198594-000066271F = <table> {
 }
 Creature-0-4248-2444-4677-198594-000266271F = <table> {
 }
 Creature-0-4254-2444-16430-189617-00006613AA = <table> {
 }
 Creature-0-4248-2444-4677-198594-0000E6271F = <table> {
 }
 Player-1390-0C6708A3 = <table> {
 }
 Creature-0-4254-2444-16430-194649-00006613AA = <table> {
 }
 Creature-0-4248-2444-4677-189632-0000662720 = <table> {
 }
 Creature-0-4248-2444-4677-194649-0000662720 = <table> {
 }
 Creature-0-4248-2444-4677-194644-0000662720 = <table> {
 }
 Creature-0-4254-2444-16430-198594-00026613AA = <table> {
 }
 Player-1390-0C129422 = <table> {
 }
 Creature-0-4254-2444-16430-198594-0000E613AA = <table> {
 }
 Creature-0-4248-2444-4677-198594-000166271F = <table> {
 }
 Creature-0-4254-2444-16430-198594-00016613AA = <table> {
 }
 Creature-0-4248-2444-4677-197833-000066271F = <table> {
 }
 Player-1315-0AEEAB81 = <table> {
 }
 Player-1329-09CFF970 = <table> {
 }
 Creature-0-4254-2444-16430-198594-00006613AA = <table> {
 }
}
p_updateAurasCurrentUnit = "Player-1621-0790FF50"

**Comment by neuvo123** [comment]
I was testing the new version and were not gaining any till I did one mind control and after it the lua started spam again

ill try uninstall completely and try with a fresh install

this lua is with version [100002.14-release]

57x NameplateAuras/src/NameplateAuras.lua:82: attempt to index local '_unitAuraInfo' (a nil value)
[string "@NameplateAuras/src/NameplateAuras.lua"]:82: in function `func'
[string "@FrameXML/AuraUtil.lua"]:46: in function <FrameXML/AuraUtil.lua:38>
[string "@FrameXML/AuraUtil.lua"]:65: in function <FrameXML/AuraUtil.lua:58>
[string "@NameplateAuras/src/NameplateAuras.lua"]:96: in function <NameplateAuras/src/NameplateAuras.lua:85>
[string "@NameplateAuras/src/NameplateAuras.lua"]:1516: in function `?'
[string "@NameplateAuras/src/NameplateAuras.lua"]:1432: in function <NameplateAuras/src/NameplateAuras.lua:1432>

Locals:
_unitAuraInfo = nil
(*temporary) = <table> {
 608454 = <table> {
 }
 608753 = <table> {
 }
 603615 = <table> {
 }
 596781 = <table> {
 }
 595081 = <table> {
 }
 607304 = <table> {
 }
 596849 = <table> {
 }
 608665 = <table> {
 }
 607805 = <table> {
 }
 595007 = <table> {
 }
 608668 = <table> {
 }
 596856 = <table> {
 }
}
(*temporary) = "Player-3686-057F2CB2"
(*temporary) = "attempt to index local '_unitAuraInfo' (a nil value)"
PlayerAurasPerGuid = <table> {
 Creature-0-4254-2444-16430-189632-00006613AA = <table> {
 }
 Creature-0-3892-2444-7006-194643-0000668E43 = <table> {
 }
 Creature-0-4248-2444-4677-194643-000066271F = <table> {
 }
 Creature-0-4248-2444-4677-189632-0000662720 = <table> {
 }
 Player-3686-06EA0A91 = <table> {
 }
 Creature-0-3892-2444-7006-189632-0000668E43 = <table> {
 }
 Player-3691-059E4542 = <table> {
 }
 Creature-0-3892-2444-7006-198594-0000668E43 = <table> {
 }
 Player-581-0A5335F8 = <table> {
 }
 Player-1390-0C6708A3 = <table> {
 }
 Player-1408-07588DC9 = <table> {
 }
 Creature-0-4254-2444-16430-194648-00006613AA = <table> {
 }
 Creature-0-3892-2444-7006-198594-0001E68E43 = <table> {
 }
 Creature-0-3892-2444-7006-194648-0000668E46 = <table> {
 }
 Creature-0-4248-2444-4677-194649-0000662720 = <table> {
 }
 Player-3692-09EE1CF2 = <table> {
 }
 Player-3692-04FF4052 = <table> {
 }
 Creature-0-3892-2444-7006-194649-0000668E46 = <table> {
 }
 Creature-0-3892-2444-7006-189617-0000668E46 = <table> {
 }
 Player-1390-0C52AD4F = <table> {
 }
 Player-1315-0AEEAB81 = <table> {
 }
 Creature-0-4254-2444-16430-198594-0001E613AA = <table> {
 }
 Creature-0-4254-2444-16430-198594-00006613AA = <table> {
 }
 Creature-0-3892-2444-7006-198594-0002668E43 = <table> {
 }
 Creature-0-3892-2444-7006-198594-0000E68E43 = <table> {
 }
 Creature-0-4254-2444-16430-194644-00006613AB = <table> {
 }
 Creature-0-4248-2444-4677-198594-000166271F = <table> {
 }
 Creature-0-4254-2444-16430-197833-00006613AA = <table> {
 }
 Creature-0-4254-2444-16430-198594-00016613AA = <table> {
 }
 Player-612-06233DBB = <table> {
 }
 Creature-0-3892-2444-7006-198594-0001668E43 = <table> {
 }
 Creature-0-4248-2444-4677-198594-000066271F = <table> {
 }
 Player-1390-0C4C8AAA = <table> {
 }
 Player-1390-0C0E7B3B = <table> {
 }
 Creature-0-4248-2444-4677-189617-000066271F = <table> {
 }
 Player-1621-0790FF50 = <table> {
 }
 Creature-0-4248-2444-4677-194644-0000662720 = <table> {
 }
 Creature-0-4248-2444-4677-198594-0000E6271F = <table> {
 }
 Creature-0-4248-2444-4677-198594-000266271F = <table> {
 }
 Creature-0-4254-2444-16430-198594-00026613AA = <table> {
 }
 Creature-0-4254-2444-16430-194643-00006613AA = <table> {
 }
 Creature-0-4248-2444-4677-198594-0001E6271F = <table> {
 }
 Creature-0-3892-2444-7006-194644-0000668E46 = <table> {
 }
 Player-1390-0C58082B = <table> {
 }
 Player-1408-09A5A323 = <table> {
 }
 Player-1315-0C1FD5A7 = <table> {
 }
 Creature-0-4248-2444-4677-194648-0000662720 = <table> {
 }
 Player-1390-0C129422 = <table> {
 }
 Creature-0-3892-2444-7006-197833-0000668E46 = <table> {
 }
 Creature-0-4254-2444-16430-189617-00006613AA = <table> {
 }
 Creature-0-4254-2444-16430-194649-00006613AA = <table> {
 }
 Creature-0-4248-2444-4677-197833-000066271F = <table> {
 }
 Player-3686-057F2CB2 = <table> {
 }
 Player-1329-09CFF970 = <table> {
 }
 Creature-0-4254-2444-16430-198594-0000E613AA = <table> {
 }
}
p_updateAurasCurrentUnit = "Player-3686-057F2CB2"

**Comment by casualshammy** [comment]
Hmm... Are you sure this is version 100002.14? Could you please post here the whole nameplateauras folder as zip file?

2023/02/11 0:57:07 neuvo123 ***@***.***>:

**Comment by neuvo123** [comment]
yup, i used overwatch to update the addon and it was showing 100002.14

i uninstalled it now entirely and made fresh install and trying to see if i can replicate the error conditions or if the luas are gone

**Comment by neuvo123** [comment]
la 11. helmik. 2023 klo 0.39 casualshammy ***@***.***)
kirjoitti:

**Comment by neuvo123** [comment]
Only got one lua after the full uninstall and fresh installation of 100002.14 after playing one rbg and it doesnt look to be nameplateauras related but another blizz ui bug i imagine

I have sent my nameplateauras folder as .rar through email as requested anyways

I keep on testing if the lua occurs again but so far it looks like it might been solved via the update

ps. This is a awesome addon and thank you for ur all work on with it

1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:126: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:638: in function <FrameXML/EditModeManager.lua:617>
[string "=[C]"]: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:564: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:743: in function `UpdateGridLayout'
[string "@FrameXML/ActionButton.lua"]:348: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:801: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:196: in function <FrameXML/ActionButton.lua:193>

**Comment by neuvo123** [comment]
Havent been able replicate any of this lua again after the changes u made, closing this as i believe it to be fixed thank you alot casualshammy the addon is 10/10 :)
