### ISSUE TITLE
Import profile not working on Wotlk classic.

### ISSUE THREAD

**Issue by roo182** [casualshammy/NameplateAuras#184]
Hey,

There seems to be an issue with importing a profile using the string from the export profile. I've heard others also having a similar issue.

Here is the lua error:
`Message: ...terface/AddOns/NameplateAuras/src/options-dialog.lua:484: attempt to index field 'EnabledZoneTypes' (a nil value)
`
And stack: 
`.terface/AddOns/NameplateAuras/src/options-dialog.lua:484: attempt to index field 'EnabledZoneTypes' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/NameplateAuras/src/options-dialog.lua"]:484: in function <...terface/AddOns/NameplateAuras/src/options-dialog.lua:469>
[string "@Interface/AddOns/NameplateAuras/src/options-dialog.lua"]:511: in function 'func'
[string "@Interface/AddOns/NameplateAuras/src/options-dialog.lua"]:54: in function 'OnIconGroupChanged'
[string "@Interface/AddOns/NameplateAuras/src/options-dialog.lua"]:46: in function 'GuiOnProfileChanged'
[string "@Interface/AddOns/NameplateAuras/src/NameplateAuras.lua"]:328: in function 'ReloadDB'
[string "@Interface/AddOns/NameplateAuras/src/options-dialog.lua"]:5160: in function 'OnAcceptFunc'
[string "@Interface/AddOns/NameplateAuras/libs/LibRedDropdown-1.0/LibRedDropdown-1.0.lua"]:830: in function <...Auras/libs/LibRedDropdown-1.0/LibRedDropdown-1.0.lua:829>`

It should be recreatable by exporting a profile and trying to reimport it.

Thanks

**Comment by casualshammy** [comment]
Hello, sorry for the late reply.
Fixed in `30401.5-release`

**Comment by roo182** [comment]
Thanks a lot- it works :)
