### ISSUE TITLE
Feature Request: Casted Aura

### ISSUE THREAD

**Issue by rukk1** [casualshammy/NameplateAuras#189]
Hi, would you consider adding an option to add casted debuffs/totems/guardians?  For instance a rogue using Deathmark would trigger an icon.

**Comment by casualshammy** [comment]
Hi,
I have another addon for this 😁. It works as enemy cooldown tracker: https://github.com/casualshammy/NameplateCooldowns

**Comment by rukk1** [comment]
Ah I already use that, was more interested to see if someone was bursting.  It's something that the unofficial version of Flyplatebuffs can do, but the addon's a bit janky and would prefer a nice GUI like your addon with the feature that rely on a bit.  Thanks for taking a look though :)
