### ISSUE TITLE
Blizzard Icons

### ISSUE THREAD

**Issue by Aikryo** [casualshammy/NameplateAuras#190]
Tryd to make own icons (only border) with Illustrator and exported the images as type .tga, but it doesn't work - got everytime a blanket picture. 

Would be nice we got a option to set the icons as Blizzard style and mby a support with masque.

Feedback: Thanks for The Addon, you do a really really good job with this, nice Addon <3 <3 <3

**Comment by casualshammy** [comment]
Hi! Thanks for your kind words.
About Masque support: https://github.com/casualshammy/NameplateAuras/issues/186#issuecomment-1464875790

IIRC tga should be 
  - edge sizes must be a power of 2 (64x64, 128x64, 256x128);
  - 32 bpp RGBA (with or w/o RLE)
Also please check path to your texture - it should be smth like `Interface\AddOns\NameplateAuras\media\custom-border`.

I'll try to add the ability to set build-in Blizz borders.

**Comment by Aikryo** [comment]
Thank you very much! A Implement of the Blizzard-Icon Function would be rly nice. Greetings :-D

**Comment by casualshammy** [comment]
I have managed to add experimental Masque support in the latest release (100002.20-release).
