### ISSUE TITLE
Frama strata setting doesn't work for me.

### ISSUE THREAD

**Issue by MiniFredx** [casualshammy/NameplateAuras#191]
I have both the options set to "Background" but the icons from nauras still covers up everything it goes in front of as if it was the highest level of strata. I have tried all the other settings as well, but nothing gets it to stop covering up my nameplates, weakauras and everything else it goes in front of. I made sure that the other things were set to a higher strata as well.

**Comment by casualshammy** [comment]
Do you use any nameplate addons? Could you please post a screenshot of NAuras' options dialog (`Size & position` tab) and an example of incorrect icon placement?
