### ISSUE TITLE
Addon doesn't show interrupts on channel spells

### ISSUE THREAD

**Issue by ezamosch** [casualshammy/NameplateAuras#192]
I noticed that addon doesn't show interrupts on channel spells.
Example:
https://www.veed.io/view/725b90ee-1462-427e-8934-3365d36f54bb?panel=share
1) I interrupt flash light and inerrupt icon showed.
2) I interrupt pennance and interrupt icon didn't show, but you can see that I did inerrupt via portret big debuffs prove (first ran out sillence effect and then it was inerrupt effect):

**Comment by casualshammy** [comment]
Hello,
Unfortunately, there are channeling spells which do not trigger any events upon interruption. As a result, there is no reliable method for tracking interruptions of these spells.
