### ISSUE TITLE
I'm want to make a feature request to the NameplateAuras addon developer.

### ISSUE THREAD

**Issue by NamTaeHo** [casualshammy/NameplateAuras#193]
I find it inconvenient to have to select 'Show My Auras Only' for each spell individually. Can a feature be created to set this option globally?

**Comment by NamTaeHo** [comment]
![WOW nameplate capture](https://user-images.githubusercontent.com/122771195/229302604-6b3eccb6-ffb3-4210-baa3-1854c597c33f.PNG)

**Comment by casualshammy** [comment]
Hello! Sorry for the late reply.
Impemented in `100100.0-release`
