### ISSUE TITLE
Nothing appears

### ISSUE THREAD

**Issue by ghost** [casualshammy/NameplateAuras#197]
I am not being able to visualize the addon in a normal way in the world or M+, I can see the auras in ''test mode'' but when I close it I stop seeing them, I don't know if it has to do with the language or something (I'm from Latin America) I have everything updated, I don't know if I should see the addon in English?
![wefwe](https://github.com/casualshammy/NameplateAuras/assets/116979996/80120f68-babe-4551-a0b6-a3da3b7e611b)

**Comment by casualshammy** [comment]
Hello!

1. Just in case - it's impossible to see auras above *friendly* nameplates in dungeons (m+ too): https://www.wowhead.com/news/addons-and-friendly-nameplates-in-patch-7-2-260801

2. Could you please post a screenshot of `General` sections of addon's options window? May be you have some restrictive filters enabled. 

3. What locale are you playing? `Latin American Spanish` or `Brazilian Portuguese`? Please make sure you have added spells by id, link or localized name.
