### ISSUE TITLE
not an issue a request

### ISSUE THREAD

**Issue by palach68** [casualshammy/NameplateAuras#202]
hello^^ i just dont know where i could write u a request for the addon so i try it here.. would it be (or is already?) possible to add an option to make nameplates of enemys glow/place an icon of usable spell at % of their health? like killshot or drain soul at 25% / execute 20% etc.. would be awesome! thank you for your work love the addon

**Comment by casualshammy** [comment]
Hello! Thanks for your kind words.
Unfortunately, there are no either feature to highlight nameplates nor display conditions for auras. I have plans to implement user provided lua conditions, but there is not ETA.
BTW such nameplate glow should be easy to get if you're using WeakAuras, I'm pretty sure there are a couple of auras for it.
