### ISSUE TITLE
ADD OWN SPELLS ? -WOW.CLASSIC-

### ISSUE THREAD

**Issue by 4b4forg** [casualshammy/NameplateAuras#203]
Hello, 

Really cool addons thanks for all the work.

I've started using it in classic, and saw that many of my auras as hunter (this is just for exemple) are not showing, like **concussive shot**, or **Wing clip** and others. 

Is there a way to add spells without showing all auras cast by me ? 
Maybe I'm missing something, 

Thanks a lot for the great work.

**Comment by casualshammy** [comment]
Hello.
Thanks for your kind words. What version of the addon are you using?

**Comment by 4b4forg** [comment]
Hey, using the last one from curseforge : NameplateAuras-11401.3-release-classic.zip !
