### ISSUE TITLE
All of the options are missing from the menu in HC Classic

### ISSUE THREAD

**Issue by BuckerzMcNasty** [casualshammy/NameplateAuras#204]
Hey there! I'm such a fan of this addon, I absolutely love it! The really strange thing is that it works just fine in Wrath of the Lich King Classic, I've got all the Options in the left hand bar ( Alpha, Text Timer, Icon borders, etc.)  I just started playing HC Classic and downloaded version 11401.3 classic from curseforge and when I pull up the menu to tweek everything, The only parameters that are there are General, as well as Size & Position. Nothing else shows up.  Any work arounds or things that I could try? Thank you for all of your hard work. 
                            Bucky

**Comment by casualshammy** [comment]
Hi! Please try out the latest version `11404.1-release`
