### ISSUE TITLE
Icon Sizes Using Icon Groups

### ISSUE THREAD

**Issue by ehargarther** [casualshammy/NameplateAuras#205]
I recently attempted to create a second icon group to display a few spells different from the initial group. When doing this, changing the size of the icons on the secondary group also changes it for the first group despite the settings being different between groups.

**Comment by casualshammy** [comment]
Hello!
Thank you very much for reporting. I've fixed this bug in `100107.0-release`. 
Also, user can explicitly override spell's icon's size without some messy calculations in options dialog now (strings are not built yet 😅):
![image](https://github.com/casualshammy/NameplateAuras/assets/4965168/0c9f66d3-bbf9-4e3f-a585-cfdabb0d551b)

**Comment by ehargarther** [comment]
Amazing - looks to be working perfectly, thanks so much!
