### ISSUE TITLE
Lotation filter not working properly

### ISSUE THREAD

**Issue by Diablolock** [casualshammy/NameplateAuras#206]
Hi!

The "Battlegrounds" filter is not working in a 10-15man BG and the "40ppl Battleground" is working both in Epics and Regular BGs.

![image](https://github.com/casualshammy/NameplateAuras/assets/41457628/43690b76-0d2b-4db3-bc25-0097a61ff71a)

I also would like to suggest to make the name of the filter the same you did on your other addon (NameplateCooldowns): "Epic Battlegrounds"

**Comment by casualshammy** [comment]
Hi,
Thanks for reporting.
Hmm, according to API Arathi now is 40 ppl bg... 😅 I did some changes and I hope version `100107.2-release` is ok.
Localization changes will be applied on sunday.
