### ISSUE TITLE
The Interrupts icon sizing doesnt work

### ISSUE THREAD

**Issue by respekten** [casualshammy/NameplateAuras#207]
I cant change the interrupts icon size, whatever i change to it doesnt work.

**Comment by casualshammy** [comment]
Hi,
Thanks for reporting. Please try out the latest version `100107.3-release`

**Comment by respekten** [comment]
I have tried new version. Still doesnt work. Interrupt icon size always follow the default icon size whatever you change it to.

**Comment by respekten** [comment]
i downloaded  the 100105.6-release and it works

**Comment by respekten** [comment]
100107.1-release and 100107.2-release . Doesnt work.

**Comment by casualshammy** [comment]
`100107.3-release` seems to be working properly. Could you please explain what do you do to test it?

**Comment by respekten** [comment]
100107.3-release actually works, i downloaded wrong version. thx very much
