### ISSUE TITLE
Spell Options Not Displayed

### ISSUE THREAD

**Issue by Snooperbesnoopin** [casualshammy/NameplateAuras#208]
Hey, WoW Classic playere here. Several months ago I was playing quite a lot, and this addon worked absolutely fine however since returning about a week ago, NameplateAuras fails to A. Display any auras when outside of Test Mode and B. Does not even have the options for me to add/change/select spells for display. Was wondering if there was something I was missing-

Currently on the up to date patch for both Classic and for NameplateAuras on Curseforge

**Comment by casualshammy** [comment]
Hi! Please try out the latest version `11404.1-release`

**Comment by BuckerzMcNasty** [comment]
That fixed it! Thank you so much. You rock
