### ISSUE TITLE
Interrupts now showing in all Icon Groups

### ISSUE THREAD

**Issue by ehargarther** [casualshammy/NameplateAuras#209]
Hello,

I had previously opened a request about the icon sizing sticking for all icon groups despite them being different. That was fixed and was working exactly as expected - thank you!

Now, the built in interrupt tracking appears to also be showing in that new icon group and was not previously. These are not tracked spells and just built into the interrupt tracking section so I cannot set groups on them myself. Any chance we could get an option to set icon groups for interrupts?

**Comment by casualshammy** [comment]
Hello!
I'm not sure I correctly understood you, but interrupt tracker can be enabled/disabled per each icon group. Just select icon group and then go to interrupt tracker settings and disable it.

**Comment by ehargarther** [comment]
I didn't realize every option page was specific to the group you had selected in the top left - thank you!
