### ISSUE TITLE
Corruption without duration

### ISSUE THREAD

**Issue by iddqd1984** [casualshammy/NameplateAuras#21]
Hey,

great addon, keep up the good work! One issue is hindering me to use it: i play an affliction warlock, often with Absolute Corruption which gives the spell an infinite duration, Unfortunately, Nauras doesnt recognize this and always shows the glow around the debuff, which is totally distracting me. Anything to do about this?

Thanks!

**Comment by casualshammy** [comment]
Hi,
Please post output of '/nauras debug' command.

**Comment by iddqd1984** [comment]
PRESS ESC TO CLOSE THIS WINDOW
PRESS CTRL+A AND THEN CTRL+C TO COPY THIS TEXT

Version: r148

InPvPCombat: true
Number of nameplates: 3
Number of visible nameplates: 1
EnabledAurasInfo count: 182
AurasPerNameplate count: 3

LIST OF ENABLED ADDONS----------
    Auctionator
    AuctionatorMiniFeatures
    Details
    Details_DmgRank
    Details_DeathGraphs
    Details_DpsTuning
    Details_EncounterDetails
    GTFO
    HandyNotes
    HandyNotes_BattleForAzerothTreasures
    HandyNotes_Arathi
    KeystoneRollCall
    MacroToolkit
    MacroToolkitIcons
    Masque
    Masque_ElvUIesque
    Masque_FlatSquares
    NameplateAuras
    PersonalLootHelper
    Postal
    PremadeGroupsFilter
    RaiderIO
    RaiderIO_DB_EU_A
    RaiderIO_DB_EU_H
    SharedMedia
    Simulationcraft
    TalentSetManager
    TidyPlates_ThreatPlates
    WeakAuras
    WorldQuestTracker
    xCT+
    DejaCharacterStats
    AddOnSkins
    ElvUI
    DBM-Core
    DBM-DefaultSkin
    DBM-StatusBarTimers

CONFIG----------
    StacksTextAnchor: BOTTOMRIGHT (string)
    InterruptsEnabled: true (boolean)
    InterruptsUseSharedIconTexture: false (boolean)
    HideBlizzardFrames: true (boolean)
    StacksFontScale: 1 (number)
    DefaultIconSize: 35 (number)
    InterruptsGlow: true (boolean)
    TimerTextUseRelativeScale: true (boolean)
    InterruptsShowOnlyOnPlayers: false (boolean)
    IconAnchor: LEFT (string)
    TimerTextSize: 20 (number)
    TimerTextYOffset: 0 (number)
    TimerTextXOffset: 0 (number)
    ShowAurasOnPlayerNameplate: false (boolean)
    Additions_ExplosiveOrbs: true (boolean)
    SortMode: 2 (number)
    StacksFont: NAuras_TeenBold (string)
    StacksTextXOffset: -3 (number)
    Font: NAuras_TeenBold (string)
    IconXOffset: 0 (number)
    IconYOffset: 50 (number)
    InterruptsIconSize: 45 (number)
    TimerTextAnchor: CENTER (string)
    ShowBuffBorders: true (boolean)
    ShowDebuffBorders: true (boolean)
    FontScale: 1 (number)
    DefaultSpellsLastSetImported: 2 (number)
    UseDimGlow: false (boolean)
    StacksTextAnchorIcon: BOTTOMRIGHT (string)
    IconSpacing: 1 (number)
    ShowAboveFriendlyUnits: true (boolean)
    FullOpacityAlways: false (boolean)
    TimerStyle: 1 (number)
    TimerTextAnchorIcon: CENTER (string)
    BorderThickness: 1 (number)
    FrameAnchor: CENTER (string)
    StacksTextYOffset: 5 (number)
    AlwaysShowMyAuras: false (boolean)
    MinTimeToShowTenthsOfSeconds: 3 (number)

LIST OF SPELLS----------
    Life Cocoon: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Soul Harvest: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Skull Bash: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Eye for an Eye: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Dark Archangel: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Netherstorm Flag: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Shadow Blades: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Ring of Frost: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Mending Bandage: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Blind: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Counter Shot: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Fel Eruption: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Leap: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Warbringer: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Ice Block: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Freezing Arrow: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Counterspell: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Garrote - Silence: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Cyclone: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Dark Pact: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Arcane Power: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    War Banner: ALL; DEBUFF; 35; nil; true; true; nil; 1; nil;
    Way of the Crane: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Scatter Shot: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Intimidating Roar: ALL; DEBUFF; 35; nil; true; true; nil; 1; nil;
    Darkness: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Spear Hand Strike: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Fear: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Hex: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Howl of Terror: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Storm Bolt: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Icy Veins: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Maim: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Spell Reflection: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Optical Blast: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Meteor Strike: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Mass Entanglement: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Cloak of Shadows: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Blinding Light: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Pain Suppression: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Fortifying Brew: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Entangling Roots: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Combat Readiness: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Mesmerize: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Storm, Earth, and Fire: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Ice Form: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Unstable Affliction: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Last Word: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Gnaw: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Divine Shield: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Intimidating Shout: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Binding Shot: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Metamorphosis: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Between the Eyes: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Icebound Fortitude: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Sin and Punishment: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Imprison: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Call Felhunter: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Blinding Sleet: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Wyvern Sting: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Roar of Sacrifice: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Mind Control: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Guardian Spirit: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Kick: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Avenger's Shield: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Repentance: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Corruption: MYAURAS; DEBUFF; 35; nil; false; true; nil; 2; 5;
    Evasion: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Ice Floes: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Mind Freeze: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Agony: MYAURAS; DEBUFF; 35; nil; false; true; nil; 2; 5;
    Touch of Karma: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Guardian of the Forgotten Queen: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Freeze: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Nature's Vigil: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Spectral Sight: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Serenity: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Explosion: DISABLED; DEBUFF; 35; nil; nil; nil; nil; nil; 2592000;
    Psychic Scream: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Dampen Harm: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Charge: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Pummel: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Power Infusion: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Die by the Sword: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Freezing Trap: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Holy Word: Chastise: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Shield Wall: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Astral Shift: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Shackle Undead: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Pillar of Frost: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Disarm: ALL; DEBUFF; 35; nil; true; true; nil; 1; nil;
    Archangel: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Master's Call: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Prismatic Barrier: ALL; BUFF; 35; nil; true; true; nil; 1; nil;
    Horde Flag: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Axe Toss: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Blessing of Sacrifice: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Netherwalk: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Voidform: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Mind Bomb: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Fists of Fury: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Shockwave: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Grounding Totem Effect: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Ethereal Form: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Kidney Shot: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Alliance Flag: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Frost Nova: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Berserker Rage: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Cheap Shot: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Barkskin: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Adrenaline Rush: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Aegis of Light: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Sap: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Static Charge: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Survival Instincts: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Blessing of Freedom: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Solar Beam: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Bladestorm: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Cheat Death: ALL; BUFF; 35; nil; true; true; nil; 1; nil;
    Shadow Reflection: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Mortal Coil: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Avatar: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Shadow Lock: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Hammer of Justice: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Zen Meditation: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Entrapment: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Muzzle: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Polymorph: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Tracker's Net: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Unending Resolve: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Silence: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Strangulate: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Aspect of the Turtle: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Incapacitating Roar: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Rake: ALL; ANY; 35; table: 000002109D8B2950; true; true; nil; 1; nil;
    Corpse Shield: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Shambling Rush: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Smoke Bomb: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Sharpen Blade: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Banish: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Nether Bond: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Seduction: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Nether Ward: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Soul Reaper: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Asphyxiate: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Blessing of Protection: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Gouge: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Ironbark: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Ardent Defender: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Anti-Magic Shell: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Blazing Barrier: ALL; BUFF; 35; nil; true; true; nil; 1; nil;
    Shadowfury: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Narrow Escape: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Guardian of Ancient Kings: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Chaos Nova: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Blur: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Diffuse Magic: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Killing Spree: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Celestial Alignment: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Ranger's Net: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Leg Sweep: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Temporal Shield: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Rebuke: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Master of the Elements: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Recklessness: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Dispersion: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Deterrence: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Paralysis: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Vampiric Embrace: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Predatory Swiftness: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Dragon's Breath: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Duel: ALL; DEBUFF; 35; nil; true; true; nil; 1; nil;
    Earthgrab: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Bloodlust: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Casting Circle: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Disrupt: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Wind Shear: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Aura Mastery: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Innervate: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Ascendance: ALL; ANY; 35; nil; true; true; nil; 1; nil;
    Spell Lock: DISABLED; DEBUFF; 45; nil; nil; nil; nil; nil; 2592000;
    Mighty Bash: ALL; ANY; 35; nil; true; true; nil; 1; nil;

**Comment by casualshammy** [comment]
Hi,
This bug is fixed in [the latest release (80000.5-release)](https://wow.curseforge.com/projects/nameplateauras/files/2620257).
