### ISSUE TITLE
Function request, suggestion. Using the parent layer/Using the parent transparency

### ISSUE THREAD

**Issue by Vokilog** [casualshammy/NameplateAuras#210]
Hello. I use your addon, I really like its convenience and functionality. Thank you so much for your work.

I would like to make a suggestion, maybe it can be added quickly. It's about Using the parent layer/Using the parent transparency.

Using the parent transparency of icons will fix the problem when the nameplate is transparent and the icon is not, it looks bad, especially when there are walls or pillars.

![image](https://github.com/casualshammy/NameplateAuras/assets/78691391/8393f627-dd08-4e9c-8400-be1a5e67dc3f)

Using the parent layer should fix the problem when the icon of the neighboring nameplate is visible on top of the target nameplate

![image](https://github.com/casualshammy/NameplateAuras/assets/78691391/554cc5b0-a5c4-4801-b878-57d76d9dd7ef)

icons are superimposed on top of the target's nameplate, even if you put a "background" layer

I hope that you will be able to do it =)
Thank you.

**Comment by casualshammy** [comment]
Привет!

Раньше так и было, но насколько я помню, это вызывало какие-то баги при работе с аддонами, меняющими неймплейты. 
Грубо говоря, нельзя взять от неймплейтов только прозрачность или слой фрейма, наследуется сразу всё, в т.ч. масштаб, анимации и прочее. Учитывая, что иконки имеют свои настройки масштаба и даже анимацию, это приводило к нежелательным эффектам. Поэтому сейчас иконки не привязаны к неймплейтам.

Как вариант, могу предложить воспользоваться настройками прозрачности в NA: 
![image](https://github.com/casualshammy/NameplateAuras/assets/4965168/a99c5cfb-6a5c-4f80-a122-5a91d8f197a7)

**Comment by Vokilog** [comment]
Да, я знаю эту настройку, но она не решает не одну из двух проблем о которых я написал выше.

Я не предлагаю полностью менять логику или отказаться от текущих вариантов настроек.
Я предложил добавить ещё 1 пункт к уже имеющимся.
Если это вызывает конфликты с сторонними нейплейтами, об этом можно сделать уведомление, что настройка доступна только для родных нейплейтов Blizzard.

Я не сильно разбирал код нейплейтов, но почти на 100% уверен, что это реализуемо.
Я пробовал реализовывать отображение бафов/дебафов с помощью кастомной ВАшки в WeakAuras, и использование родительских настроек от нейплейтов, работают на бафы/дебафы.

-------------------

Yes, I know this setting, but it does not solve any of the two problems I wrote about above.

I am not suggesting to completely change the logic or abandon the current settings options.
I suggested adding 1 more item to the existing ones.
If this causes conflicts with third-party nameplate, you can make a notification about it that the setting is only available for native Blizzard nameplate.

I didn't really understand the code of the nameplates, but I'm almost 100% sure that this is feasible.
I tried to implement the display of buffs / debuffs using a custom WA in WeakAuras, and the use of parental settings from the namepletes, work on buffs / debuffs.

**Comment by casualshammy** [comment]
Почему бы и нет :) Добавил в версии `100107.8-release`. 
Однако, как я говорил, следует учесть что на итоговые параметры иконок (размер. прозрачность и т.д.) будут влиять собственные параметры полосок хп.

![image](https://github.com/casualshammy/NameplateAuras/assets/4965168/cdb756e9-68dc-4d62-8fc7-ea687d0ef7a0)

**Comment by Vokilog** [comment]
Большое спасибо.
Быстрый тест показал, что обе проблемы, из первого поста, решаются этой настройкой.

--------------------------------------------------------
Thank you very much.
A quick test showed that both problems from the first post are solved by this setting.
