### ISSUE TITLE
show only my auras

### ISSUE THREAD

**Issue by shershenator** [casualshammy/NameplateAuras#211]
It's not a bug report, I just can't figure out how to show only my auras on targets, is it possible?

**Comment by casualshammy** [comment]
If you want 1) show all auras on all nameplates but 2) show only your auras on your target, then there is not such feature.
If you want to show only your auras on all nameplates, then there are 2 ways:
- wipe all auras from the list of auras and then enable `Always show auras cast by myself` feature in `General` section of options window;

OR

- see image below:
![image](https://github.com/casualshammy/NameplateAuras/assets/4965168/179d266b-c448-40ed-bc0b-3368fcc0a6f2)

**Comment by shershenator** [comment]
I still can't make it show **only my dot on every target**, so when there are many mobs I can see which target is without MY dot. It shows the dot I specify on targets, but not only mine, from other players as well.

**Comment by casualshammy** [comment]
Sorry, I know it's a bit late, but - are you sure you have this option enabled for your dot?

![image](https://github.com/casualshammy/NameplateAuras/assets/4965168/16d591ba-9965-4bc2-be3b-9a0360481907)
