### ISSUE TITLE
stop work with old profile

### ISSUE THREAD

**Issue by QbikQT** [casualshammy/NameplateAuras#214]
Not show cc or other stuff after update, this issue only on ru client
![2023-11-25 113601](https://github.com/casualshammy/NameplateAuras/assets/81636100/6654a172-b549-4561-aad0-ffc36cef6e6a)

**Comment by casualshammy** [comment]
Hello,
Ru client? But it seems like you have spell names in english. Maybe you have used en client and then switched to ru?
Lua errors (if any) will be helpful.
