### ISSUE TITLE
New rune spells

### ISSUE THREAD

**Issue by mayshmoreno** [casualshammy/NameplateAuras#216]
Can you add nameplate aura spells for the new rune spells in Season of Discovery? For instance rogue's Between The Eyes

**Comment by casualshammy** [comment]
Hello,
Why you don't want to add it by yourself? TBH I'm a bit struggle to determine which auras is important and which not, especially because I don't play SoD.

**Comment by mayshmoreno** [comment]
> Hello,
> Why you don't want to add it by yourself? TBH I'm a bit struggle to determine which auras is important and which not, especially because I don't play SoD.

I would definitely! I tried using the spell ID on Wowhead but it didnt seem to work. Are there any other ways to add?

**Comment by casualshammy** [comment]
Internally NAuras using spell names. Have you tried to add spell by it's name?

**Comment by mayshmoreno** [comment]
Yes I tried "Between the Eyes" and I get "Spell seems to be nonexistent"

**Comment by casualshammy** [comment]
Please try the latest classic release (`11500.0-release`)
