### ISSUE TITLE
Can't modify spells

### ISSUE THREAD

**Issue by brassard123** [casualshammy/NameplateAuras#217]
Modifying all the hots and dots at once works well. But it doesn't seem to work in the Spells section.

I allowed to show tooltips over my hots, getting the proper Spell id, but I can't modify.

I've also tried each and every id available.

Basically I want to hide the long buffs such as thorns and motw and just keep the hots and dots.

**Comment by casualshammy** [comment]
Hello,
I'm not sure I got your idea. If you haven't enabled `Always show auras cast by myself` option then only auras in the auras list will be shown.
