### ISSUE TITLE
cant disable "edge" on swipe effects

### ISSUE THREAD

**Issue by jaimerydev** [casualshammy/NameplateAuras#218]
hi, 

in the patch or at some point a "swipe" effect got added to all aura timers which is quite distracting and was not there in the past. I'm naming it as such as this is how it is called in weakauras.

![image](https://github.com/casualshammy/NameplateAuras/assets/32485267/2a9a675f-80f9-4f5a-819b-6d74c2edb27b)

To be clear, I mean the yellow edge.

**Comment by casualshammy** [comment]
Hi,
Sorry for the late reply. NameplateAuras uses standard cooldown animation and there wasn't any changes. For instance, my aura timers had this swipe effect for years. Maybe you have uninstalled some addon that changes cooldown style globally?

**Comment by sdaynight** [comment]
@jamesmckeever
Did you solve this issue?
the same issue happened to me tonight.. i didnt uninstalled or updated any addons before this happened

**Comment by casualshammy** [comment]
I've added the option to override default behavior:
![image](https://github.com/casualshammy/NameplateAuras/assets/4965168/742e8c47-98f8-4f6d-b3d8-b22ffb9ed559)
Hope it helps.

**Comment by sdaynight** [comment]
it works well! TY!!

I think blizzard recently added some cartoon effects to in-game
