### ISSUE TITLE
See Only My Buffs

### ISSUE THREAD

**Issue by Zaef** [casualshammy/NameplateAuras#219]
Hello! I am unable to find a setting (and I could be completely missing it so I apologize) to only see my buffs on the target. For example, if I have Renew on a target, I don't want to see other player's Renew, just mine. Is there a way to set that up? If not, could we add it? It is confusing on my RDruid when I am unsure which HoTs are mine or another Druid's, similar for my other Healing classes.

**Comment by casualshammy** [comment]
Hello!
Sorry, I can't provide screenshot from the game now, but there is per-aura option (first checkbox in aura options iirc).

**Comment by Zaef** [comment]
Hello! Thank you for getting back to me!  :)

Do you mean "Hide Blizzard's aura frames (except player)"?

**Comment by casualshammy** [comment]
![image](https://github.com/casualshammy/NameplateAuras/assets/4965168/fc20a079-935a-491e-b1af-743592e01c1a)
![image](https://github.com/casualshammy/NameplateAuras/assets/4965168/6c8f94f0-8c18-4c41-8456-8810daa12a8b)

**Comment by Zaef** [comment]
I never would have found that! Thank you SO much! <3

Do you want me to delete the report I made on GitHub?
