### ISSUE TITLE
Profiles are not shared between characters when 'copying' profile from one side to the other

### ISSUE THREAD

**Issue by tatianavy** [casualshammy/NameplateAuras#220]
Hi. I setup a profile with a LOT of settings and different spell sizes on my warlock. I exported that profile to share with my husband and it worked. Today I wanted that same profile on my Paladin, so I went to the profiles and copied the one from my lock - didn't work - but it did change the settings for example hammer of justice was showing with 60x60 size in the settings but was not showing that in the nameplates. I found out that the only way to get the same profile was to actually import it in my paladin, the same string I had shared with my husband.

ps - i did a second try of this on a different character for my husband and ye, only way to make it work was to import again the string, copying profiles won't work.

Thank you :)

**Comment by casualshammy** [comment]
Hi,
I can't reproduce this bug with my profiles. Could you please provide your import string?
