### ISSUE TITLE
Can't open the border color setting

### ISSUE THREAD

**Issue by Amazzinx** [casualshammy/NameplateAuras#222]
Hello.
For some reason, I can't open the border color setting, when I click on the color selection window, nothing happens. Everything used to work fine.
Thank you.
![screen](https://github.com/casualshammy/NameplateAuras/assets/157214312/3baa3819-83ee-478b-b451-a1f75146c107)

**Comment by casualshammy** [comment]
Hello,
Thank you very much for reporting; I have pushed fixed version (100205.1-release).
