### ISSUE TITLE
Can't add spells I'd like to track

### ISSUE THREAD

**Issue by JuicedGG** [casualshammy/NameplateAuras#223]
Was looking to start using this addon for PVP but I can't add the following spells:
- Deathmark (360194)
- Asphyxiate (221562)
- Anti-magic zone (51052)
- Survival tactics ( 202746)
- Blessing-of-spellwarding (204018)

And there are probably more but I stopped searching for them.

**Comment by casualshammy** [comment]
Could you please explain what you mean by 'you can't add a spell'? Didn't you find a way to do it, or there is some error?

**Comment by JuicedGG** [comment]
When I go to the spells tab and I type the spell ID or the name (checked multiple times for spelling errors) than I press enter nothing happens. The spell is not added and I don't get an error either.

**Comment by casualshammy** [comment]
Is the 'Add/import aura' button red the moment you press Enter? Or it is black? You have to wait until it becomes red.

**Comment by JuicedGG** [comment]
That's weird. I disabled the add-on, enabled it again and now it's working. I can find all the above spells.
