### ISSUE TITLE
Bulk add spells

### ISSUE THREAD

**Issue by Soromeister** [casualshammy/NameplateAuras#224]
At the moment, there is no way to bulk add spells.

I understand there is an import string that can be used but it's not clear where you can make the import string, since it should be different than the profile import string.

It would be nice to have the possibility to add multiple spells to the list with a separator, kind of like `;` or `,` and then have them all imported as a result.

**Comment by casualshammy** [comment]
Hi,
Now NAuras accepts semicolon-separated list of spell ids. Make sure you're using version `100205.6-release` or newer.
