### ISSUE TITLE
Can't change the color of the timer text or stack text in Classic Era SoD #BUG

### ISSUE THREAD

**Issue by Theguyxd** [casualshammy/NameplateAuras#225]
Hey! I just want to start off by saying that I love the addon and I use it in every version of the game. Right now however I'm having an issue with changing the color of any timer text or stack text on the auras in Classic. I'm using the version of the addon labled for 1.15 and I get this lua erro whenever I try to "apply" the color change.

Message: [string "*ColorPickerFrame.xml:80_OnClick"]:2: attempt to call field 'swatchFunc' (a nil value)
Time: Thu Feb 22 00:46:13 2024
Count: 1
Stack: [string "*ColorPickerFrame.xml:80_OnClick"]:2: attempt to call field 'swatchFunc' (a nil value)
[string "*ColorPickerFrame.xml:80_OnClick"]:2: in function <[string "*ColorPickerFrame.xml:80_OnClick"]:1>

Locals: self = ColorPickerOkayButton {
 SetTextToFit = <function> defined @Interface/SharedXML/SecureUIPanelTemplates.lua:244
 Right = Texture {
 }
 Left = Texture {
 }
 fitTextWidthPadding = 40
 FitToText = <function> defined @Interface/SharedXML/SecureUIPanelTemplates.lua:249
 Text = ColorPickerOkayButtonText {
 }
 0 = <userdata>
 Middle = Texture {
 }
 fitTextCanWidthDecrease = true
}
button = "LeftButton"
down = false
(*temporary) = nil
(*temporary) = "attempt to call field 'swatchFunc' (a nil value)"

Thanks again and hope you're doing well! Cheers.

**Comment by casualshammy** [comment]
Hi! Thanks for reporting!
Fixed in version `11501.0-release`
