### ISSUE TITLE
Auras are not display in the party in the dange 

### ISSUE THREAD

**Issue by DmytroSy** [casualshammy/NameplateAuras#228]
Hello!
Auras are not displayd in the party in the dange, but in the same time they work well outside a dange, I can see my auras above people's nameplates.
But it for some reason doesn't work in the dange when you are in the party. I don't see my auras (baffs) above group members nameplates.
But I can see debuffs (DoT) above enemy templates in the dange.
Can you help please?

**Comment by casualshammy** [comment]
Hello!
Please read this: https://github.com/casualshammy/NameplateAuras/issues/91#issuecomment-717119489

**Comment by DmytroSy** [comment]
Oh, thank you very much, I didn't even know about that...
