### ISSUE TITLE
Question about "Display auras on nameplates of friendly units"

### ISSUE THREAD

**Issue by raphaeloliveira** [casualshammy/NameplateAuras#229]
Hi, is it possible to have this option only enabled in arena? I would like to not see it in other places of the game if possible.

Thanks!

![image](https://github.com/casualshammy/NameplateAuras/assets/2700131/ac9bcc97-864c-40aa-b842-43b369853bd5)

**Comment by casualshammy** [comment]
Hi,
Just in case it is still actual - implemeted in version `100206.3-release`

**Comment by 0kamiyasha** [comment]
Just throwing it out there whatever was done to fix this topic is now making auras show on friendlies even if the above "display on friendly units" is unchecked
