### ISSUE TITLE
Incorrect OmniCC timer color

### ISSUE THREAD

**Issue by MaiRukki** [casualshammy/NameplateAuras#23]
The timer color in OmniCC is set to white when duration is longer than 1 mins, yellow when duration is less than 1 min and turn red when 5 secs left but it always appears white in NameplateAuras.

This happens for OmniCC 8.0.7. Still working properly for the eariler version of OmniCC

**Comment by casualshammy** [comment]
Hi, 
Erm, maybe it's not a problem of NAuras?
tullamods/OmniCC#269

**Comment by MaiRukki** [comment]
Fixed after OmniCC update 8.0.8
