### ISSUE TITLE
Enabling "My Auras Only"

### ISSUE THREAD

**Issue by Aldem23** [casualshammy/NameplateAuras#231]
I've been searching online for ages. I can't seem to find if this exists or not. I'm trying to see my spells only (like Living Bomb in SoD) but I can see other mages as well. Any help is appreciated!

Thanks!

**Comment by casualshammy** [comment]
Hello!
You can set visibility on per-spell basis


![image](https://github.com/casualshammy/NameplateAuras/assets/4965168/9cc0c6ff-aac2-46ad-a8ba-37643c212792)
