### ISSUE TITLE
Cata Beta

### ISSUE THREAD

**Issue by tellinz** [casualshammy/NameplateAuras#232]
any update coming out for Cata beta/release? Currently does not work at all on the Beta

**Comment by devcolm** [comment]
The quick fix seems to be to simply bump one of the addon's libraries.

Replace the **DRList-1.0** lib located in _Interface\AddOns\NameplateAuras\libs_
with the cata version
https://github.com/wardz/DRList-1.0/releases/tag/v1.4.3

Tested a few of the old wotlk buffs I have configured as well as some of the new, Cataclysm exclusive (Mind Spike, Paralysis). Some new icon textures are missing (majority that I need seems to work), but it's better than nothing until the addon is updated.

**Comment by Moonfirebeam** [comment]
@devcolm devcolm how exactly do u do that with that link? i see 4 differnt links from that. can u give better instructions please

**Comment by Moonfirebeam** [comment]
@devcolm

**Comment by devcolm** [comment]
> @devcolm devcolm how exactly do u do that with that link? i see 4 differnt links from that. can u give better instructions please

This is the file that you need to download.
![obraz](https://github.com/casualshammy/NameplateAuras/assets/13589575/12451759-46ac-4d02-9cfd-ee7b847df651)

Then, in this folder, delete (or rename) existing **DRList-1.0** folder, then unzip the downloaded file here.
![obraz](https://github.com/casualshammy/NameplateAuras/assets/13589575/7f20b99c-59e1-4fbf-96e3-a7cb5fecfd52)

**Comment by casualshammy** [comment]
Hello,
I've pushed version for Cata (40400.0-release)

**Comment by Flattyxgg** [comment]
I tried all spell id for grounding totem(8177). Doesn't show the icon
