### ISSUE TITLE
question: how to enable for the followers in follower dungeons

### ISSUE THREAD

**Issue by ScottIngram** [casualshammy/NameplateAuras#233]
I can't get any auras to show on the follower healthbars in follower dungeons

**Comment by casualshammy** [comment]
Hi,
Please read this: https://github.com/casualshammy/NameplateAuras/issues/91#issuecomment-717119489

**Comment by ScottIngram** [comment]
Thanks for the answer.  I bet a tooltip or note of some sort in the addon itself would prevent people like me coming here and pestering you for the same answer again and again.
