### ISSUE TITLE
Patch 11.0.2 broke NameplateAuras!

### ISSUE THREAD

**Issue by GLopez12** [casualshammy/NameplateAuras#234]
It won't load for me anymore.

**Comment by DevTyldor** [comment]
Does load for me, but gives me this: 
![image](https://github.com/user-attachments/assets/58b5c584-8a3c-4ec1-9aa1-b6d56e15bb51)

**Comment by ReallyMadCow** [comment]
same with lots of errors including the one Tyldor mentioned

**Comment by shrekin** [comment]
The same situation in my case. There are errors in invariant.lua:2 (attempt to call global GetSpellInfo), utils.lua:15 (GetSpellTexture), spells.lua:34 (SpellNameById), NameplateAuras.lua (deepcopy) :317 :373 :1577 :1520, and NameplateAuras.lua (db) :1481.

**Comment by Daptonic** [comment]
Same, here is my full error:

```
6x NameplateAuras/src/NameplateAuras.lua:1483: attempt to index upvalue 'db' (a nil value)
[string "@NameplateAuras/src/NameplateAuras.lua"]:1483: in function <NameplateAuras/src/NameplateAuras.lua:1481>

Locals:
currentTime = 574609.587000
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'db' (a nil value)"
db = nil
NameplatesVisible = <table> {
}
AurasPerNameplate = <table> {
}
```

`14x NameplateAuras/src/NameplateAuras.lua:317: attempt to call field 'deepcopy' (a nil value)
[string "@NameplateAuras/src/NameplateAuras.lua"]:317: in function <NameplateAuras/src/NameplateAuras.lua:305>
[string "@NameplateAuras/src/NameplateAuras.lua"]:373: in function `OnStartup'
[string "@NameplateAuras/src/NameplateAuras.lua"]:1577: in function `?'
[string "@NameplateAuras/src/NameplateAuras.lua"]:1520: in function <NameplateAuras/src/NameplateAuras.lua:1520>

Locals:
aceDBDefaults = <table> {
 profile = <table> {
 }
}
(*temporary) = <table> {
 BORDER_TYPE_CUSTOM = 2
 SPITEFUL_SPELL_ID = 69861
 BORDER_TYPE_BUILTIN = 1
 AURA_SORT_MODE_NONE = 1
 GLOW_TYPE_AUTOUSE = 3
 SHOW_ON_PLAYERS = 2
 AllAuraIconFrames = <table> {
 }
 ICON_GROW_DIRECTION_LEFT = 2
 EPIC_BG_ZONE_IDS = <table> {
 }
 Nameplates = <table> {
 }
 SHOW_ON_PLAYERS_AND_NPC = 1
 CONST_SPELL_MODE_DISABLED = 1
 EXPLOSIVE_ORB_NPC_ID_AS_STRING = "120651"
 ICON_ANIMATION_DISPLAY_MODE_NONE = 1
 BORDER_TEXTURES = <table> {
 }
 ICON_ALIGN_CENTER = 3
 SHOW_ON_NPC = 3
 MAX_AURA_ICON_SIZE = 75
 AURA_SORT_MODE_AURATYPE_EXPIRE = 6
 ICON_ANIMATION_DISPLAY_MODE_ALWAYS = 2
 ICON_ALIGN_BOTTOM_LEFT = 1
 INSTANCE_TYPE_SCENARIO = "scenario"
 AURA_TYPE_ANY = 3
 ICON_GROW_DIRECTION_DOWN = 4
 ICON_ALIGN_TOP_RIGHT = 2
 ICON_GROW_DIRECTION_RIGHT = 1
 GLOW_TYPE_ACTIONBUTTON = 2
 VERY_LONG_COOLDOWN_DURATION = 2592000
 AURA_TYPE_DEBUFF = 2
 INSTANCE_TYPE_ARENA = "arena"
 ICON_ANIMATION_TYPE_ALPHA = 2
 AURA_SORT_MODE_CUSTOM = 7
 ICON_ANIMATION_DISPLAY_MODE_THRESHOLD = 3
 INSTANCE_TYPE_PVP = "pvp"
 CONST_SPELL_MODE_MYAURAS = 3
 AURA_SORT_MODE_EXPIRETIME = 2
 EXPLOSIVE_ORB_SPELL_ID = 240446
 DR_TEXTURES = <table> {
 }
 EventFrame = Frame {
 }
 CONST_SPELL_MODE_ALL = 2
 AURA_TYPE_BUFF = 1
 INSTANCE_TYPE_RAID = "raid"
 GLOW_TYPE_NONE = 1
 GLOW_TYPE_PIXEL = 4
 GLOW_TYPE_ACTIONBUTTON_DIM = 5
 ICON_GROW_DIRECTION_UP = 3
 Interrupts = <table> {
 }
 INSTANCE_TYPE_PARTY = "party"
 INSTANCE_TYPE_UNKNOWN = "unknown"
 BORDER_TYPE_DISABLED = 3
 INSTANCE_TYPE_PVP_BG_40PPL = "pvp_bg_40ppl"
 GLOW_TIME_INFINITE = 2592000
 SPITEFUL_NPC_ID_STRING = "174773"
 AURA_SORT_MODE_ICONSIZE = 4
 INSTANCE_TYPE_NONE = "none"
}
(*temporary) = nil
(*temporary) = <table> {
 profile = <table> {
 }
}
(*temporary) = "attempt to call field 'deepcopy' (a nil value)"
addonTable = <table> {
 BORDER_TYPE_CUSTOM = 2
 SPITEFUL_SPELL_ID = 69861
 BORDER_TYPE_BUILTIN = 1
 AURA_SORT_MODE_NONE = 1
 GLOW_TYPE_AUTOUSE = 3
 SHOW_ON_PLAYERS = 2
 AllAuraIconFrames = <table> {
 }
 ICON_GROW_DIRECTION_LEFT = 2
 EPIC_BG_ZONE_IDS = <table> {
 }
 Nameplates = <table> {
 }
 SHOW_ON_PLAYERS_AND_NPC = 1
 CONST_SPELL_MODE_DISABLED = 1
 EXPLOSIVE_ORB_NPC_ID_AS_STRING = "120651"
 ICON_ANIMATION_DISPLAY_MODE_NONE = 1
 BORDER_TEXTURES = <table> {
 }
 ICON_ALIGN_CENTER = 3
 SHOW_ON_NPC = 3
 MAX_AURA_ICON_SIZE = 75
 AURA_SORT_MODE_AURATYPE_EXPIRE = 6
 ICON_ANIMATION_DISPLAY_MODE_ALWAYS = 2
 ICON_ALIGN_BOTTOM_LEFT = 1
 INSTANCE_TYPE_SCENARIO = "scenario"
 AURA_TYPE_ANY = 3
 ICON_GROW_DIRECTION_DOWN = 4
 ICON_ALIGN_TOP_RIGHT = 2
 ICON_GROW_DIRECTION_RIGHT = 1
 GLOW_TYPE_ACTIONBUTTON = 2
 VERY_LONG_COOLDOWN_DURATION = 2592000
 AURA_TYPE_DEBUFF = 2
 INSTANCE_TYPE_ARENA = "arena"
 ICON_ANIMATION_TYPE_ALPHA = 2
 AURA_SORT_MODE_CUSTOM = 7
 ICON_ANIMATION_DISPLAY_MODE_THRESHOLD = 3
 INSTANCE_TYPE_PVP = "pvp"
 CONST_SPELL_MODE_MYAURAS = 3
 AURA_SORT_MODE_EXPIRETIME = 2
 EXPLOSIVE_ORB_SPELL_ID = 240446
 DR_TEXTURES = <table> {
 }
 EventFrame = Frame {
 }
 CONST_SPELL_MODE_ALL = 2
 AURA_TYPE_BUFF = 1
 INSTANCE_TYPE_RAID = "raid"
 GLOW_TYPE_NONE = 1
 GLOW_TYPE_PIXEL = 4
 GLOW_TYPE_ACTIONBUTTON_DIM = 5
 ICON_GROW_DIRECTION_UP = 3
 Interrupts = <table> {
 }
 INSTANCE_TYPE_PARTY = "party"
 INSTANCE_TYPE_UNKNOWN = "unknown"
 BORDER_TYPE_DISABLED = 3
 INSTANCE_TYPE_PVP_BG_40PPL = "pvp_bg_40ppl"
 GLOW_TIME_INFINITE = 2592000
 SPITEFUL_NPC_ID_STRING = "174773"
 AURA_SORT_MODE_ICONSIZE = 4
 INSTANCE_TYPE_NONE = "none"
}
aceDB = nil`

**Comment by casualshammy** [comment]
~~I've pushed version `110002.0-release`. At the first glance it works. 😁~~
No, version `110002.1-release` is better
