### ISSUE TITLE
positioning issue for friendly nameplate auras

### ISSUE THREAD

**Issue by max-striker** [casualshammy/NameplateAuras#237]
Is it possible to fix the position of nameplate auras on friendly bars somehow? (there is too much gap) thanks
nameplates are from threatplates addon

![Screenshot_1](https://github.com/user-attachments/assets/c9b06e9a-65c3-4ea8-a38c-286d61333c19)

**Comment by casualshammy** [comment]
Please update to version `110002.4-release` and then try to enable this option:
![image](https://github.com/user-attachments/assets/dce65397-42a5-4690-820f-11c42402392f)

**Comment by max-striker** [comment]
@casualshammy thanks alot! appreciated
