### ISSUE TITLE
Request: Turn on dispellable buffs in PvE only?

### ISSUE THREAD

**Issue by GLopez12** [casualshammy/NameplateAuras#240]
I don't want to see dispellable buffs in PvP; it's too cluttered. But I do like seeing them in PvE, especially M+. Would it be possible to add the option to show dispellable buffs in PvE only, particularly M+?

I love the addon, and appreciate all your work on it!

**Comment by casualshammy** [comment]
Hi,
Implemented in version `110002.10-release`
![image](https://github.com/user-attachments/assets/55b3f205-8c02-463d-80d3-f679d5daa9c7)

**Comment by GLopez12** [comment]
Amazing, thank you!
