### ISSUE TITLE
Can not turn off pets getting icons. 

### ISSUE THREAD

**Issue by Dodge524** [casualshammy/NameplateAuras#244]
I have tried everything i can think of, but I really hope there is a way we can turn off icons on pets. I have pets turned off right now in cvar becuase it is just to much seeing black arrow on every pet running around the screen. Thanks for your amazing addon tho (:

**Comment by casualshammy** [comment]
Hi,
Added per-aura option in version `110005.0-release`:
![image](https://github.com/user-attachments/assets/411c5c3b-5bc8-4eef-82f4-1976e2b8ef4b)

**Comment by Dodge524** [comment]
Bro you are legit the man!!!! I can’t believe you did this. Actually changes the game for me. I just had all pets and totems turned off. I’m going to look for a donation link to try and help you keep this add on alive. Honestly is the single best add on in the game. If I could only pick one to use in pvp it would be this. Thank you so much! Sent from my iPhoneOn Nov 3, 2024, at 12:18 PM, casualshammy ***@***.***> wrote:﻿
Hi,
Added per-aura option in version 110005.0-release:
image.png (view on web)
