### ISSUE TITLE
HOTs Do Not Show On Player Nameplates In Dungeons

### ISSUE THREAD

**Issue by MaydieWilldie** [casualshammy/NameplateAuras#246]
HOTs Do Not Show On Player Nameplates In Dungeons. Works outside of them only.

**Comment by casualshammy** [comment]
Hi,
Please read [this](https://github.com/casualshammy/NameplateAuras/issues/91#issuecomment-717119489)

**Comment by MaydieWilldie** [comment]
Well that sucks! Appreciate you pointing out that post. This has been frustrating. Blizzard's bars suck for tracking this.
