### ISSUE TITLE
Cannot customize nameplatecooldowns

### ISSUE THREAD

**Issue by methdiet** [casualshammy/NameplateAuras#25]
![addon](https://user-images.githubusercontent.com/43887435/46544837-a42d1b00-c892-11e8-8c36-1e74fac34d4b.png)

I dont know whats going on, but why is it so difficult to customize what spells i want to see? I have to scroll through every spell in the game, disable it, then rescroll all the way back down. Gets to be a real pain in the ass once you're getting close to the bottom. Maybe add class spells, with one click tracking/untracking. In addition, once i customize what spells i want to see and dont want to see, the add on doesnt work at all... it doesnt track any spells. i cant customize it at all. But the default of tracking every spell in the game is very annoying, so much clutter. I think this addon is amazing, i just wish i could get it to work properly.

**Comment by methdiet** [comment]
I've also uninstalled and reinstalled a hand full of times, tinkered around with all settings. Cant figure it out.

**Comment by casualshammy** [comment]
Hi,
1. The list of spells will be saving its position in next release.
2. I've wiped my settings and then made some changes to the list of spells. Addon works as intended. Can you confirm that addon isn't working with new clean settings profile?
