### ISSUE TITLE
New app: Consolidate 'Roll the Bones' buffs into single icon

### ISSUE THREAD

**Issue by Jalopyy** [casualshammy/NameplateAuras#26]
https://www.wowhead.com/spell=193316/roll-the-bones

https://www.wowhead.com/spell=199603/skull-and-crossbones
https://www.wowhead.com/spell=193358/grand-melee
https://www.wowhead.com/spell=193357/ruthless-precision
https://www.wowhead.com/spell=193359/true-bearing
https://www.wowhead.com/spell=199600/buried-treasure
https://www.wowhead.com/spell=193356/broadside

Add an app that counts the # of buffs gained from an RTB and consolidate them within a single icon, using the RTB texture. Use stack text (or just a giant number over the texture) to signify the # of active buffs. The duration of all the buffs will always be the same, and making rerolling the buffs before they run out will clear the old ones, so there shouldn't be any problem with extraneous conditions/coding to make this work.

**Comment by casualshammy** [comment]
Apps are intended as highly specialized things. For example, you will see explosive orbs in dungeons only and they all are enemies - you should kill them at once. I can make it this way: consolidated buffs' icon will have default size and will be shown above enemy bars only.
