### ISSUE TITLE
Getting the following error constantly while addon is enabled

### ISSUE THREAD

**Issue by Nemedon** [casualshammy/NameplateAuras#27]
163x NameplateAuras\src\NameplateAuras-80000.7-release.lua:1065: attempt to index field 'UnitFrame' (a nil value)
NameplateAuras\src\NameplateAuras-80000.7-release.lua:1065: in function <NameplateAuras\src\NameplateAuras.lua:1007>
NameplateAuras\src\NameplateAuras-80000.7-release.lua:823: in function <NameplateAuras\src\NameplateAuras.lua:772>
NameplateAuras\src\NameplateAuras-80000.7-release.lua:1127: in function `?'
NameplateAuras\src\NameplateAuras-80000.7-release.lua:1105: in function <NameplateAuras\src\NameplateAuras.lua:1105>

Locals:
frame = NamePlate1 {
 0 = <userdata>
 NAurasIconsCount = 0
 unitFrame = ElvUI_NamePlate1 {
 }
 NAurasIcons = <table> {
 }
}
counter = 1
totalWidth = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined @NameplateAuras\src\NameplateAuras.lua:826
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'UnitFrame' (a nil value)"
AurasPerNameplate = <table> {
 (null) = <table> {
 }
}
GetTime = <function> defined =[C]:-1
SortAurasForNameplate = <function> defined @NameplateAuras\src\NameplateAuras.lua:857
pairs = <function> defined =[C]:-1
SpellNameByID = <table> {
 19647 = "Spell Lock"
 88611 = "Smoke Bomb"
 187707 = "Muzzle"
 221527 = "Imprison"
 31935 = "Avenger's Shield"
 51271 = "Pillar of Frost"
 200108 = "Ranger's Net"
 33206 = "Pain Suppression"
 29166 = "Innervate"
 231665 = "Avenger's Shield"
 118 = "Polymorph"
 104773 = "Unending Resolve"
 23333 = "Horde Flag"
 61336 = "Survival Instincts"
 205369 = "Mind Bomb"
 236320 = "War Banner"
 122783 = "Diffuse Magic"
 130736 = "Soul Reaper"
 20066 = "Repentance"
 125174 = "Touch of Karma"
 212638 = "Tracker's Net"
 132409 = "Spell Lock"
 216113 = "Way of the Crane"
 34976 = "Netherstorm Flag"
 408 = "Kidney Shot"
 2094 = "Blind"
 108839 = "Ice Floes"
 152173 = "Serenity"
 212640 = "Mending Bandage"
 91802 = "Shambling Rush"
 137639 = "Storm, Earth, and Fire"
 53480 = "Roar of Sacrifice"
 196098 = "Soul Harvest"
 31661 = "Dragon's Breath"
 117526 = "Binding Shot"
 147362 = "Counter Shot"
 48707 = "Anti-Magic Shell"
 74001 = "Combat Readiness"
 114052 = "Ascendance"
 99 = "Incapacitating Roar"
 47528 = "Mind Freeze"
 22812 = "Barkskin"
 5484 = "Howl of Terror"
 12472 = "Icy Veins"
 120954 = "Fortifying Brew"
 6770 = "Sap"
 198589 = "Blur"
 211881 = "Fel Eruption"
 30283 = "Shadowfury"
 31821 = "Aura Mastery"
 1766 = "Kick"
 194223 = "Celestial Alignment"
 47481 = "Gnaw"
 122278 = "Dampen Harm"
 171152 = "Meteor Strike"
 10060 = "Power Infusion"
 93985 = "Skull Bash"
 6789 = "Mortal Coil"
 1833 = "Cheap Shot"
 19386 = "Wyvern Sting"
 64695 = "Earthgrab"
 47585 = "Dispersion"
 221703 = "Casting Circle"
 205191 = "Eye for an Eye"
 236077 = "Disarm"
 51690 = "Killing Spree"
 9484 = "Shackle Undead"
 198817 = "Sharpen Blade"
 19263 = "Deterrence"
 207167 = "Blinding Sleet"
 12042 = "Arcane Power"
 86659 = "Guardian of Ancient Kings"
 235313 = "Blazing Barrier"
 122 = "Frost Nova"
 51514 = "Hex"
 6552 = "Pummel"
 119381 = "Leg Sweep"
 236748 = "Intimidating Roar"
 87204 = "Sin and Punishment"
 102342 = "Ironbark"
 2139 = "Counterspell"
 240446 = "Explosion"
 78675 = "Solar Beam"
 108271 = "Astral Shift"
 1022 = "Blessing of Protection"
 1776 = "Gouge"
 1330 = "Garrote - Silence"
 188501 = "Spectral Sight"
 196555 = "Netherwalk"
 197862 = "Archangel"
 115268 = "Mesmerize"
 124974 = "Nature's Vigil"
 16166 = "Master of the Elements"
 54216 = "Master's Call"
 871 = "Shield Wall"
 132169 = "Storm Bolt"
 102359 = "Mass Entanglement"
 605 = "Mind Control"
 198111 = "Temporal Shield"
 179057 = "Chaos Nova"
 228049 = "Guardian of the Forgotten Queen"
 5782 = "Fear"
 236273 = "Duel"
 163505 = "Rake"
 198144 = "Ice Form"
 1044 = "Blessing of Freedom"
 69369 = "Predatory Swiftness"
 273432 = "Bound by Shadow"
 37506 = "Scatter Shot"
 200166 = "Metamorphosis"
 115078 = "Paralysis"
 31850 = "Ardent Defender"
 1719 = "Recklessness"
 207810 = "Nether Bond"
 273556 = "Ichor Transfusion"
 8122 = "Psychic Scream"
 339 = "Entangling Roots"
 196718 = "Darkness"
 105771 = "Charge"
 57994 = "Wind Shear"
 136634 = "Narrow Escape"
 106839 = "Skull Bash"
 199683 = "Last Word"
 31117 = "Unstable Affliction"
 15487 = "Silence"
 132168 = "Shockwave"
 108194 = "Asphyxiate"
 118038 = "Die by the Sword"
 105421 = "Blinding Light"
 152151 = "Shadow Reflection"

**Comment by casualshammy** [comment]
Thnak you for report.
