### ISSUE TITLE
Have this error after every arena game finish. 

### ISSUE THREAD

**Issue by Sensorzp** [casualshammy/NameplateAuras#28]
11x NameplateAuras\src\NameplateAuras-80000.7-release.lua:680: attempt to index field 'UnitFrame' (a nil value)
NameplateAuras\src\NameplateAuras-80000.7-release.lua:680: in function `UpdateAllNameplates'
NameplateAuras\src\NameplateAuras-80000.7-release.lua:1236: in function <NameplateAuras\src\NameplateAuras.lua:1232>

Locals:
force = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
}
(for control) = NamePlate20 {
 0 = <userdata>
 NAurasIconsCount = 1
 unitFrame = ElvUI_NamePlate20 {
 }
 NAurasFrame = <unnamed> {
 }
 NAurasIcons = <table> {
 }
}
nameplate = NamePlate20 {
 0 = <userdata>
 NAurasIconsCount = 1
 unitFrame = ElvUI_NamePlate20 {
 }
 NAurasFrame = <unnamed> {
 }
 NAurasIcons = <table> {
 }
}
(*temporary) = nil
(*temporary) = NamePlate20 {
 0 = <userdata>
 NAurasIconsCount = 1
 unitFrame = ElvUI_NamePlate20 {
 }
 NAurasFrame = <unnamed> {
 }
 NAurasIcons = <table> {
 }
}
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'UnitFrame' (a nil value)"
pairs = <function> defined =[C]:-1
Nameplates = <table> {
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
 (null) = true
}
db = <table> {
 StacksTextAnchor = "BOTTOMRIGHT"
 DebuffBordersDiseaseColor = <table> {
 }
 InterruptsEnabled = false
 InterruptsUseSharedIconTexture = false
 HideBlizzardFrames = false
 StacksFontScale = 1
 DefaultIconSize = 25
 AlwaysShowMyAuras = false
 TimerTextUseRelativeScale = false
 InterruptsShowOnlyOnPlayers = false
 IconAnchor = "LEFT"
 DebuffBordersPoisonColor = <table> {
 }
 TimerTextSoonToExpireColor = <table> {
 }
 Additions_Raid_Zul = true
 TimerTextSize = 14
 TimerTextXOffset = 0
 MinTimeToShowTenthsOfSeconds = 1
 StacksTextColor = <table> {
 }
 ShowAurasOnPlayerNameplate = false
 Additions_ExplosiveOrbs = false
 SortMode = 1
 StacksFont = "NAuras_TeenBold"
 StacksTextXOffset = -3
 BorderThickness = 1
 FontScale = 1
 BuffBordersColor = <table> {
 }
 TimerTextUnderMinuteColor = <table> {
 }
 ShowBuffBorders = false
 DebuffBordersCurseColor = <table> {
 }
 InterruptsIconSize = 45
 TimerTextAnchor = "CENTER"
 IconXOffset = 0
 FrameAnchor = "CENTER"
 TimerTextLongerColor = <table> {
 }
 InterruptsGlow = false
 DebuffBordersMagicColor = <table> {
 }
 DefaultSpellsLastSetImported = 2
 UseDimGlow = false
 StacksTextAnchorIcon = "BOTTOMRIGHT"
 IconSpacing = 3
 ShowAboveFriendlyUnits = false
 FullOpacityAlways = true
 TimerStyle = 1
 CustomSpells2 = <table> {
 }
 Font = "Expressway"
 TimerTextYOffset = 0
 TimerTextAnchorIcon = "CENTER"
 StacksTextYOffset = 5
 ShowDebuffBorders = false
 IconYOffset = 35
 DebuffBordersOtherColor = <table> {
 }
}
SML = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 SetDefault = <function> defined @ElvUI\Libraries\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:285
 GetDefault = <function> defined @ElvUI\Libraries\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:281
 LOCALE_BIT_ruRU = 2
 UnregisterAllCallbacks = <function> defined @ElvUI\Libraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 SetGlobal = <function> defined @ElvUI\Libraries\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:272
 GetGlobal = <function> defined @ElvUI\Libraries\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:268
 List = <function> defined @ElvUI\Libraries\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:258
 HashTable = <function> defined @ElvUI\Libraries\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:254
 MediaTable = <table> {
 }
 RegisterCallback = <function> defined @ElvUI

**Comment by casualshammy** [comment]
Thank you for report.
