### ISSUE TITLE
spell blacklist

### ISSUE THREAD

**Issue by Apoxiosis** [casualshammy/NameplateAuras#29]
frankly, im not sure what all spells are included in nameplate auras, so i dont want to delete all spells then readd them case by case, could you include a checklist of spells to show/hide, or maybe a blacklist to manually remove specific spells?

unstable affliction is useless information for anyone that isnt a warlofk, and if youre a warlock, you need to have specific addons or weakauras to show your own unstable afflictions, not other warlocks as well, so this addon displaying something like UA is quite bothersome

**Comment by casualshammy** [comment]
Sorry, "blacklist for whitelist" seems to be strange.
You can set NAuras to show only your UA in UA spell options.
