### ISSUE TITLE
errors when using with elvUI

### ISSUE THREAD

**Issue by redpig68** [casualshammy/NameplateAuras#36]
Korean language Client

6x NameplateAuras\src\NameplateAuras-80100.0-release.lua:699: attempt to index field 'checkSpellID' (a number value)
NameplateAuras\src\NameplateAuras-80100.0-release.lua:699: in function <NameplateAuras\src\NameplateAuras.lua:688>
NameplateAuras\src\NameplateAuras-80100.0-release.lua:797: in function <NameplateAuras\src\NameplateAuras.lua:773>
NameplateAuras\src\NameplateAuras-80100.0-release.lua:1128: in function `?'
NameplateAuras\src\NameplateAuras-80100.0-release.lua:1106: in function <NameplateAuras\src\NameplateAuras.lua:1106>

Locals:
isBuff = false
auraName = "갈퀴 발톱"
auraCaster = nil
auraSpellID = 24331
unitIsFriend = false
spellInfo = <table> {
 enabledState = 2
 auraType = 3
 showOnEnemies = true
 showOnFriends = true
 pvpCombat = 1
 iconSize = 45
 checkSpellID = 163505
}
showInPvPCombat = 1
(*temporary) = 163505
(*temporary) = "attempt to index field 'checkSpellID' (a number value)"
db = <table> {
 StacksTextAnchor = "BOTTOMRIGHT"
 DebuffBordersDiseaseColor = <table> {
 }
 InterruptsEnabled = true
 InterruptsUseSharedIconTexture = false
 HideBlizzardFrames = true
 StacksFontScale = 1
 DefaultIconSize = 45
 InterruptsGlow = false
 TimerTextUseRelativeScale = true
 InterruptsShowOnlyOnPlayers = true
 IconAnchor = "LEFT"
 DebuffBordersPoisonColor = <table> {
 }
 DebuffBordersMagicColor = <table> {
 }
 TimerTextSize = 20
 Additions_Raid_Zul = true
 TimerTextAnchorIcon = "CENTER"
 StacksTextColor = <table> {
 }
 ShowAurasOnPlayerNameplate = false
 Additions_ExplosiveOrbs = true
 SortMode = 2
 TimerTextXOffset = 0
 BorderThickness = 2
 StacksFont = "NAuras_TeenBold"
 StacksTextXOffset = -3
 DebuffBordersCurseColor = <table> {
 }
 TimerTextUnderMinuteColor = <table> {
 }
 IconXOffset = 0
 ShowBuffBorders = true
 InterruptsIconSize = 45
 TimerTextAnchor = "CENTER"
 BuffBordersColor = <table> {
 }
 IconYOffset = 50
 TimerTextLongerColor = <table> {
 }
 DefaultSpellsLastSetImported = 2
 ShowDebuffBorders = true
 FrameAnchor = "CENTER"
 FontScale = 1
 StacksTextAnchorIcon = "BOTTOMRIGHT"
 IconSpacing = 1
 ShowAboveFriendlyUnits = true
 FullOpacityAlways = false
 TimerStyle = 1
 CustomSpells2 = <table> {
 }
 Font = "NAuras_TeenBold"
 MinTimeToShowTenthsOfSeconds = 10
 AlwaysShowMyAuras = false
 StacksTextYOffset = 5
 TimerTextYOffset = 0
 TimerTextSoonToExpireColor = <table> {
 }
 DebuffBordersOtherColor = <table> {
 }
}
EnabledAurasInfo = <table> {
 연막탄 = <table> {
 }
 충격파 = <table> {
 }
 돌진 = <table> {
 }
 얼음 방패 = <table> {
 }
 주인의 부름 = <table> {
 }
 거북의 상 = <table> {
 }
 결투 = <table> {
 }
 회피 = <table> {
 }
 어둠 = <table> {
 }
 치유 붕대 = <table> {
 }
 전투 준비 = <table> {
 }
 영혼 이동 = <table> {
 }
 물어뜯기 = <table> {
 }
 명상 = <table> {
 }
 휘감는 뿌리 = <table> {
 }
 위기 모면 = <table> {
 }
 정신 얼리기 = <table> {
 }
 도약 = <table> {
 }
 갈퀴 발톱 = <table> {
 }
 자유의 축복 = <table> {
 }
 팽이 차기 = <table> {
 }
 마비 = <table> {
 }
 눈부신 진눈깨비 = <table> {
 }
 유성 충돌 = <table> {
 }
 탈태 = <table> {
 }
 미간 적중 = <table> {
 }
 위협의 포효 = <table> {
 }
 강화주 = <table> {
 }
 기의 고치 = <table> {
 }
 영혼 수확자 = <table> {
 }
 목조르기 - 침묵 = <table> {
 }
 용의 숨결 = <table> {
 }
 발차기 = <table> {
 }
 오라 숙련 = <table> {
 }
 공포의 울부짖음 = <table> {
 }
 원소의 대가 = <table> {
 }
 혼절시키기 = <table> {
 }
 전하 충전 = <table> {
 }
 반격의 사격 = <table> {
 }
 폭풍과 대지와 불 = <table> {
 }
 잊힌 여왕의 수호자 = <table> {
 }
 호드 깃발 = <table> {
 }
 수액 수혈 = <table> {
 }
 안구 광선 = <table> {
 }
 두개골 강타 = <table> {
 }
 유혹 = <table> {
 }
 빛의 권능: 응징 = <table> {
 }
 공허의 형상 = <table> {
 }
 얼음발 = <table> {
 }
 평안 = <table> {
 }
 투사의 혼 = <table> {
 }
 주문 반사 = <table> {
 }
 태양 광선 = <table> {
 }
 구속의 사격 = <table> {
 }
 마법 차단 = <table> {
 }
 얼음 핏줄 = <table> {
 }
 지옥사냥개 부르기 = <table> {
 }
 무쇠껍질 = <table> {
 }
 무장 해제 = <table> {
 }
 분열 = <table> {
 }
 추적자의 그물 = <table> {
 }
 죄와 벌 = <table> {
 }
 고대 왕의 수호자 = <table> {
 }
 구사일생 = <table> {
 }
 행동 불가의 포효 = <table> {
 }
 황천 보호막 = <table> {
 }
 폭발 = <table> {
 }
 수호 영혼 = <table> {
 }
 대규모 휘감기 = <table> {
 }
 재갈 = <table> {
 }
 얼음같은 인내력 = <table> {
 }
 광기의 학살자 = <table> {
 }
 후려치기 = <table> {
 }
 피의 욕망 = <

**Comment by casualshammy** [comment]
That's quite strange bug, because my addon have a several checks against such errors. Tell me please, do you get this error constantly (when you see the 'Rake' spell), or it's one-time issue?

**Comment by pontab** [comment]
I have the same issue, not using ElvUI though.
