### ISSUE TITLE
Friendly units' buffs are not showing on their nameplates when in a dungeon

### ISSUE THREAD

**Issue by stavroskasidis** [casualshammy/NameplateAuras#37]
As the title says, when inside a dungeon (low-level with dungeon finder) the buffs I put on other players (e.g. Rejuvenation) are not showing. When testing my settings in Ogrimmar, eveything works as expected.

Is this some kind of limitation from Blizzard's API ?

Here are the settings that I use for Rejuvenation:
![image](https://user-images.githubusercontent.com/12549761/54389674-55897580-46a9-11e9-9bcd-339c489cdee8.png)

And here are the general settings:
![image](https://user-images.githubusercontent.com/12549761/54389818-af8a3b00-46a9-11e9-90d6-403e9d073625.png)

**Comment by casualshammy** [comment]
https://www.wowhead.com/news=260801/addons-friendly-nameplates-in-patch-7-2

**Comment by stavroskasidis** [comment]
Well this sucks ... :(
Anyway, awesome addon, thank you
