### ISSUE TITLE
Item tooltip visibility issue

### ISSUE THREAD

**Issue by stamicvs** [casualshammy/NameplateAuras#39]
Hi Casualshammy,

I encountered a weired behavior with NameplateAuras:
After 5 to 10 minutes into the game if I move the mouse over an item the tooltip is not kept inside of the screen for showing the item tooltip. I assume this happens after some aura events have ben fired. This effect happens only with Nameplate Auras if I deactivate the addon there is no issue.
This happens in the character frame to look at my items and in my bags as well.
It would be great if you can find a solution for this.
I've attached two screenshots to show this behavior.

Directly after start or reload of the game:
![Nameplate_Auras_Tooltip_Start](https://user-images.githubusercontent.com/48605567/61175222-c7b48d00-a5ab-11e9-8c8d-c84a20d04f2f.png)

After some time:
![Nameplate_Auras_Tooltip_OutofScreen](https://user-images.githubusercontent.com/48605567/61175225-d8650300-a5ab-11e9-9f39-c73d6e3fe753.png)

Thank you very much.
Bests,

Stamic

**Comment by casualshammy** [comment]
Hi!
What tooltip addon are you using?

**Comment by stamicvs** [comment]
Hi!
I am using TinyTooltip right now:
https://www.curseforge.com/wow/addons/tinytooltip
and in addition to add some information:
AzeriteTooltip for changing the Azerite information within the tooptip.
AzeritePowerWeights for showing weights on azerite traits and Pawn is also inserting information into the tooltip.
TinyTooltip is also used to change the background and border to my own layouts inserted by SharedMedia_MyMedia

Interestingly the behavior is only if I enable NameplateAuras. I also have NameplateCooldowns installed (thank you very much for this addon btw. ;) ) and with NameplateCooldowns and as a test replacement for NameplateAuras activated Auras in KuiNameplates there is no change in the tooltip.

I hope this helps you.
Thank you very much for your effort.

**Comment by casualshammy** [comment]
I'm not playing WoW now, so I can't do a proper testing (so I can't publish a new version) :( Could you please help me? This archive contains file 'NameplateAuras.lua', please put it in <YOUR WOW FOLDER\_retail_\Interface\AddOns\NameplateAuras\src> folder. Please report about results (problem persists or not). Thank you.
[NameplateAuras.zip](https://github.com/casualshammy/NameplateAuras/files/3407444/NameplateAuras.zip)

**Comment by stamicvs** [comment]
Of course I will!
I just downloaded the package and will report the result.
Thank you

**Comment by stamicvs** [comment]
Unfortunately I encountered the same issue after doing some worldquests.
I played with my Elemental Shaman so had two dots active and also saw a dot from another player on my target.
Could it be that it has something to do with the frame changes in patch 8.2?
https://us.forums.blizzard.com/en/wow/t/ui-changes-in-rise-of-azshara/202487

**Comment by casualshammy** [comment]
No, I think it is not about these changes in frame anchor. In a few words, when you place mouse over aura icon, NameplateAuras sets anchor point for tootip. I don't know why, but your tooltip addon fails to override NameplateAuras anchor and shows tooltip with incorrect anchor point. I can only suggest to disable aura tooltip in NameplateAuras's options dialog.
About dot - maybe filters allow to show this aura from another players?

**Comment by stamicvs** [comment]
Yes, I am sure that the filter is the case for the dot.
No worries, I will try to disable the aura tooltip and see what happens. If this does not change anything I will get in contact with the tooltip addon creator.
Thank you very much for your help

**Comment by stamicvs** [comment]
Ok, now after some games, I can verify that disabling the aura tooltip option solves the issue. I will get in contact with the author of TinyTooltip to maybe get a fix for the tooltip anchor override.
Thank you very much for your effort!

**Comment by LybrialsGit** [comment]
@stamicvs did you get an answer from the author of TinyTooltip?

**Comment by casualshammy** [comment]
@LybrialsGit NameplateAuras currently uses custom tooltip for auras. Do you have any issues with the latest version?

**Comment by LybrialsGit** [comment]
Hi. I was just looking for people with the same problem that I currently have and @stamicvs was the only one I found so far. I coded nameplates, auras, actionbars and many other stuff myself but I have the exact same problem like described here, meaning tooltips leaving the screen after some time and I have no clue what causes this so I hoped that maybe stamicvs had contact with the author of TinyTooltip and solved the problem so I could solve mine too ^^

**Comment by ZanderWT** [comment]
I've got this issue as well. After I mouseover a nameplateauras icon to display its tooltip, all other mouse-anchored tooltips will run off the screen. here's a video of the bug: https://www.youtube.com/watch?v=6BUf0dwncIM

The video shows the bug happening with Plater nameplates but it also happens for me with default blizzard nameplates.

It only happens with default blizzard tooltips enabled, when I use the custom nameplateauras tooltips, there's no problem

**Comment by casualshammy** [comment]
Unfortunately, there isn't simple solution for this issue. If nameplateauras will forcibly restore tooltip's anchor point, it will lead to another issues with addons that do set anchor points before displaying tooltip...
