### ISSUE TITLE
Unknown difficulty: 151

### ISSUE THREAD

**Issue by MrMime71** [casualshammy/NameplateAuras#41]
seems to come from this addon..

**Comment by casualshammy** [comment]
Please provide more info. BTW, NameplateAuras does nothing with difficulties.

**Comment by MrMime71** [comment]
im trying to reproduce it.. doesnt give any lua errors just a "debug message" like above.. 
im sorry.. but it was not your addon.. i enabled it again and i dont have the error message. 
I need to contune the search if it popps up again
