### ISSUE TITLE
Bug: Misaligned Menu

### ISSUE THREAD

**Issue by Nukme** [casualshammy/NameplateAuras#42]
version:
80200.2-release

environment:
wow bfa@windows10. zhCN

description:
The Menu tabs below SPELL are misaligned, like this
<img src="https://i.ibb.co/X2Drj2y/nauras.png" alt="nauras" border="0">

**Comment by casualshammy** [comment]
谢谢 ：）
I'll push localizations update soon. If you're good in Chinese and have spare time, please consider of translate one or two phrases [here](https://www.curseforge.com/wow/addons/nameplateauras/localization/languages/99/phrases#223050).

**Comment by Nukme** [comment]
I've put in my translation for phrases under Need Translation category. Happy to help!
