### ISSUE TITLE
Rake ( bleed and stun )

### ISSUE THREAD

**Issue by danilastepanov** [casualshammy/NameplateAuras#43]
How i can add 2 spell Rake with differen id? I need a stun larger icon and a smaller bleeding icon. When u use Rake at stealth u stun target for 3 second and bleed for 15 second. This all Rake effect with different ID's. But i can add only one Rake auras for all ID's. They all have one size. When i try add 2 diffirent Rake ID's, addons say that spell list elready have this spell. And i can set only one size for all ID's Rake spell. I try set stun effect with large size and my bleed effect with small size at nameplate. This problem only with this spell (Rake (stun ID 163505, bleed ID 155722)) all ID's have spellname Rake.

**Comment by casualshammy** [comment]
This cannot be done, for now.
