### ISSUE TITLE
Not showing with Plater

### ISSUE THREAD

**Issue by wheatbread** [casualshammy/NameplateAuras#45]
Hello!  I'd been using this addon happily for most of this expansion.  I'm now attempting to switch to Plater to try it out, but I notice that when I disable Kuinameplates and enable Plater, Nameplate Aura no longer displays any auras at all on the nameplates.  This happens even if I disable the auras that Plater provides.  Might there be any way to make it compatible with Plater?

**Comment by casualshammy** [comment]
Hello!
Plater Nameplates modifies nameplates waaay too aggressive. It's possible to hack Plater Nameplates and thus enable NameplateAuras, but Plater Nameplates forcefully rewrites changes done by NameplateAuras (that causes flickering of auras' icons). To prevent flickering, NameplateAuras should use an insane amount of CPU power. Sorry, currently WONTFIX.
