### ISSUE TITLE
Chaos Nova showing Icon of Fiery Brand

### ISSUE THREAD

**Issue by Linbarg** [casualshammy/NameplateAuras#46]
Hello Sir,

title says it. I can't change it in options, no matter what i do. Deleting and recreating doesn't work, checking Spell ID neither. it tracks the CD properly but it is kinda annoying getting used to a false icon.

Would really appreciate some advise help.

best regards

**Comment by casualshammy** [comment]
Hello!
I've pushed new release (80300.1-release), but I cannot test it by myself. I would be very pleased if you'll report if problem persists or solved.

**Comment by Linbarg** [comment]
Hey,

thanks for the fast fix. Everything seems fine now. :)
