### ISSUE TITLE
Rake Bleed and Rake Stun

### ISSUE THREAD

**Issue by Michael-Torres** [casualshammy/NameplateAuras#47]
Hello,

I am trying to add two different Spells which are tried to the same ability Rake for druid.  There's two spell IDs baked into one spell, a rake stun and rake bleed.

Stun ID: 163505
Bleed Dot ID: 155722

I can add one, but it won't let me add another because it says "Spell Already Exists (Rake)".

Any help with doing this will be greatly appreciated.  Thank you.

**Comment by casualshammy** [comment]
Duplicate #43
