### ISSUE TITLE
Timer Text

### ISSUE THREAD

**Issue by Michael-Torres** [casualshammy/NameplateAuras#48]
The Anchor Point and Anchor to Icon in the Timer Text menu does not move the timer text for me.  It always stay in the center.  I am trying to move the timer text to the topish of the icon, so I can see the spell icon better.  The color change, font scale, and x/y offset work, but not the Anchor Point or Anchor to Icon.

Any suggestions?  Thank you.

**Comment by casualshammy** [comment]
Thank you for reporting. This bug is fixed in version 80300.3-release.
