### ISSUE TITLE
[Request]Test Mode

### ISSUE THREAD

**Issue by Gennoken** [casualshammy/NameplateAuras#49]
Hey, and thank you for your work.

Was wondering why NA does not have a "test" button just like your other addon NC ???

Thx

**Comment by casualshammy** [comment]
Hi! Sorry for the late reply.
Because it's not needed. Each class has it's own buffs/auras that could be displayed at personal nameplate.

**Comment by casualshammy** [comment]
Implemented in 80300.4-release
