### ISSUE TITLE
(De-)Buffs with with same name but different spell IDs

### ISSUE THREAD

**Issue by gobacktogo** [casualshammy/NameplateAuras#52]
hey,

quick suggestion: i would like to see the stun effect of the druid ability rake at a different size than the bleed effect of the same ability when used while prowling, rake will not only apply a bleed, but a stun as well. in this case, blizzard will show 2 icons, with different IDs. what i would like to be able to do is having nauras show a small icon for my own rake bleed, but a big icon for everyone's rake stun effect.

unfortunately, trying to add both IDs separately to nauras fails at the point where nauras tells me that rake has already been added. if in deed it is somehow already possible and i am simply too dumb to go it, please excuse me.

anyways, thanks for this great addon!

**Comment by casualshammy** [comment]
Hi.
Unfortunately, this feature requires A LOT of work. In fact, it will be easier to rewrite all code base except options GUI. 
Maybe you have already tried this, but, as a quick solution, I suggest you use option 'Allow multiple instances of this aura' of 'Rake' aura.

**Comment by gobacktogo** [comment]
thanks for adding this!
