### ISSUE TITLE
Separate buff/debuff and export/import options

### ISSUE THREAD

**Issue by reypcd** [casualshammy/NameplateAuras#53]
1. If you could separate buff from debuff on the spell list, would be great, much easier to chose what we want. In my case I just want to track enemy Buffs, so I had to remove all Debuffs. 
2. It would be nice that we could chose different position to buff and debuff, different bar, not all together.
3. Is possible to export my config to save it?
3. Great addon 👍

**Comment by casualshammy** [comment]
1. User can add spell to the spell list. Addon can't check if user has correctly selected type of aura. It will be a mess. 
In the recent beta I've added a small buttons that allow to delete spells from the list directly (you don't need to select spell). Deleting spell will take only 0.5 second and one mouse click.
2. Thanks for suggestion. This feature in TODO list already, but it requires a lot of work, so I don't know when i will be able to implement it.
3. You mean backup of profile? It's pretty easy to implement. Should it be backup of all profiles, or only currently active one?
4. Thank you :)

**Comment by reypcd** [comment]
1. But is it not possible to add a spell list for Buffs and another one for Debuffs? So we don't have to read all spells to know if they are buff or debuff.
2. Nice to know. Cheer up!
3. Yes, a backup, just in case anyone need to unistall or install the game on another PC... (all profiles would be better)
Thank you for answering so quickly :)

**Comment by casualshammy** [comment]
(1) Maybe I've explained myself wrong... I can implement separate lists for default buffs and debuffs, _**but**_ user can add any spell he/she wants. What if user will add debuff spell in 'buffs' list? Let it be his own fault? If so, there will be buffs in 'debuffs' list (and vice versa), aaaaaand users will start to pm me with complaints :D I guess you want something like custom, user-defined lists of spells. It's good idea, but I think I'll make it low priority.
(3) I've just done quick test... Serialization (process of converting addon settings to string) is quite slow in WoW. I have 12 profiles with default set of spells, and serialization took ~1 min on decent pc conf. Bad thing is that game is freezes during this process. It not seems user-friendly at all. By the way, why you don't want to just copy 'WTF' folder?

**Comment by reypcd** [comment]
1. But, as you say, that would be player fault... why to add a debuff to a buff list? But it isnt 100% necessary, I have the addon working fine, so it's OK for me.
2. Yes, that is what I did, but it would be easier to share addon settings. It was just an suggestion, maybe a bad idea.
