### ISSUE TITLE
Support the anchoring to the side of a scaled nameplate

### ISSUE THREAD

**Issue by TimWinnicheck** [casualshammy/NameplateAuras#60]
**Is your feature request related to a problem? Please describe.**
Hi, 
After updating to the new version of NA, the previously working functionality is behaving strangely.
I am using NA to have an additional couple of buffs/debuffs to the right side of my nameplate (primarily CC and damage cooldowns for PvP). 
I have the Icon anchor set up to Left and Frame Anchor set up to Left as well.
Additionally, I'm using the standard ingame CVar to increase the size of the selected nameplate (SetCVar("nameplateSelectedScale", 1.3)).
How this all worked previously was that the auras were stacked to the side of the nameplate at all times, independant of whether I've selected it as a target or not. Additional auras were added to the right side of the existing auras as well, making a nice stacked line.

Unfortunately, after the last update, this behaviour seems to have changed. If the nameplate is not selected, it behaves as usual. If I select a nameplate as target though, it (obviously) gets scaled by 1.3 and the anchor point for the auras slides to the left a little bit, overlapping with the nameplate.

Here it is for unselected nameplate:
![image](https://user-images.githubusercontent.com/23016885/91778945-bdfd4700-ebfc-11ea-8ed6-d3f554e9bc0d.png)
Here's what happens when I target:
![image](https://user-images.githubusercontent.com/23016885/91778976-d8cfbb80-ebfc-11ea-81e1-123abd8f4bb5.png)

The nameplates addon I'm using is KUINameplates, but I don't think it matters, given that it's using the native CVar scaling. I've tried it out with default nameplates and anchor point seems to not move correctly as well.

**Describe the solution you'd like**
I would love for anchor point to get moved in accordance to the selected nameplate scale CVar, so my auras would not overlap with the nameplate itself.

Thank you very much for the work you're doing!

**Comment by casualshammy** [comment]
Hi,
Please check the latest release (80300.16-release).

**Comment by TimWinnicheck** [comment]
Hello again,
Thank you for your swift response!
It now works perfectly again.

Again, thank you very much!
I'll close the ticket now.
