### ISSUE TITLE
[Feature] Add strata option to icon frame or icons

### ISSUE THREAD

**Issue by timmywil** [casualshammy/NameplateAuras#65]
**Is your feature request related to a problem? Please describe.**

I recently started using Plater for nameplates. Everything works, except I noticed that the icons from Nameplate Auras are behind the nameplates rather than on top. This is despite the strata settings for all the Plater frames being set to "BACKGROUND".

Here's an example:

![image](https://user-images.githubusercontent.com/192451/93137918-37407380-f6ac-11ea-94be-63d185137c19.png)

**Describe the solution you'd like**

I think I could fix this if I could customize the strata settings on the NA icon frame containing the icons or the icons themselves.

**Comment by casualshammy** [comment]
Hello.
> I think I could fix this if I could customize the strata settings on the NA icon frame containing the icons or the icons themselves.

I have just done quick test and it seems like you cannot. If frame's parent is C (native) nameplate, this frame will be behind nameplate. No matters what frame strata you set for frame. I'll investigate a little more. If it is true, I'll set UIParent as parent for NA container frames in next beta.

**Comment by casualshammy** [comment]
I will appreciate if you'll find spare time to try out the latest beta (you can install it via Twitch client or download [directly](https://www.curseforge.com/wow/addons/nameplateauras/download/3058481)). It still has not option for frame strata, but icons are placed above nameplate (I hope). As a drawback (or feature) now you should (or can) set alpha and scale of NAuras frame by yourself, separately for nameplate of your target and other nameplates.

**Comment by timmywil** [comment]
That fixed it!
