### ISSUE TITLE
No timer or stack text showing on icons since updating

### ISSUE THREAD

**Issue by oliverfarrant** [casualshammy/NameplateAuras#68]
**Describe the bug**
Hi, I have no timer or stack text showing on icons since updating

https://i.gyazo.com/77722dfbed3ec3b34809bc491c5d5ce7.jpg

Not sure if it's omnicc dependent but omnicc is working for other icons

**Comment by casualshammy** [comment]
Thank you very much for your report! I've somehow forgot about adding two options to options window. I've uploaded a new version, it will be available in Twitch client soon. After downloading please check this two options:
![Image](https://user-images.githubusercontent.com/4965168/94801034-5c87ee00-03dd-11eb-9f84-662765e6ac21.png)
