### ISSUE TITLE
Options for setting Frame Strata

### ISSUE THREAD

**Issue by hobulian** [casualshammy/NameplateAuras#71]
I hope that there's options for setting frame strata.

**Comment by casualshammy** [comment]
Soon a new version of addon will be available for download. There are options for frame strata.
It's russian locale, but I think it's quite obvious
![Image](https://user-images.githubusercontent.com/4965168/95000614-61ee5f80-05ba-11eb-9d2e-54f90b8ed1a3.png)

**Comment by hobulian** [comment]
It's cool! Thank you!
