### ISSUE TITLE
Buffs now overlap

### ISSUE THREAD

**Issue by himfan95** [casualshammy/NameplateAuras#72]
Buffs are now overlapping each other from all nameplates. My target's buffs should always first. Now I can't tell.
![Screenshot (4)](https://user-images.githubusercontent.com/72292460/94984268-f9e33f00-050f-11eb-8717-3e298cdef2a4.png)

**Comment by casualshammy** [comment]
Soon a new version of addon will be available for download. There are options for frame strata.
It's russian locale, but I think it's quite obvious
![Image](https://user-images.githubusercontent.com/4965168/95000614-61ee5f80-05ba-11eb-9d2e-54f90b8ed1a3.png)
