### ISSUE TITLE
Small-time modding

### ISSUE THREAD

**Issue by reezlock** [casualshammy/NameplateAuras#74]
While testing the add-on, I started playing with the code a little bit to make it do some things the options don't offer atm. Just thought I'd let you know in case you want to make things like that more accessible for others. Again, the add-on already does the following perfectly, it's just an interface/accessibility issue.

(1) Timer Countdowns that appear only part of the time.
I made my Timer Text on the icons appear only at 5 seconds remaining by adding an alpha value of 0 to the color values in the Lua set for the longer times remaining (the "green" and the "yellow"). Maybe it would be useful to add an alpha slider to the color selection in the options interface?

(2) Custom Borders
I built a fancier border as a .tga file and gave it the name of one of the files in the /media subfolder (icon-border-5px.tga). By using the slider for border size, I can tell the add-on to load my custom border just fine. Maybe others would appreciate a file selection option that looks for viable .tga files in the subfolder?

**Comment by casualshammy** [comment]
- [x] Timer Countdowns that appear only part of the time. ([latest beta](https://www.curseforge.com/wow/addons/nameplateauras/download/3071234))
- [ ] Custom Borders
