### ISSUE TITLE
[feature request] Be able to test the spell you're currently adding

### ISSUE THREAD

**Issue by Mcprepped** [casualshammy/NameplateAuras#78]
I'm new to this addon so this feature may already exist but I'd like to visualize the spell I'm editing in real time. Instead of the default /nauras test I'd like to see the aura that I'm currently working on.

**Comment by casualshammy** [comment]
Hi,
Good idea. But things like aura duration (timer) or aura type (border color) will be incorrect anyway, because addon has no clue about it.

**Comment by casualshammy** [comment]
Implemented in [this release](https://www.curseforge.com/wow/addons/nameplateauras/download/3083404).
