### ISSUE TITLE
Separate Size & Position settings for debuffs showing on my character.

### ISSUE THREAD

**Issue by ulyzz** [casualshammy/NameplateAuras#83]
Hello, I love this addon but I would like to suggest a feature that would really make it better for me.

When you change the icon's size & position settings it changes for both the icons showing on other peoples nameplates and mine's. 

I'd very much like it to be separate settings, meaning, I would like to change the icon's position and size that shows on top of my character nameplate using different settings than I use on other peoples/monsters nameplates. Is that possible?

Thank you very much!

**Comment by casualshammy** [comment]
Hello.
TBH NameplateAuras isn't intended to track auras on player. There are much better tools for it (like WeakAuras). I can add an option for scale of player's nameplate, but size and position...

**Comment by ulyzz** [comment]
Oh, i thought about making this suggestion because there is an option to either show or not show the debuffs on my character.. and it would be much simpler to just use this addon rather than weak auras, but i understand what you mean.

Anyway, thanks a lot for replying!
