### ISSUE TITLE
Error when enter in M+ today ....

### ISSUE THREAD

**Issue by Pozzyx2019** [casualshammy/NameplateAuras#84]
**Describe the bug**
When enter in M+ and enter in combat bugsuck reprt this error every second ...

**To Reproduce**
12x NameplateAuras\src\NameplateAuras-90001.2-release.lua:987: Usage: <unnamed>:SetSize(width, height)
[string "=[C]"]: in function `SetSize'
[string "@NameplateAuras\src\NameplateAuras-90001.2-release.lua"]:987: in function <NameplateAuras\src\NameplateAuras.lua:976>
[string "@NameplateAuras\src\NameplateAuras-90001.2-release.lua"]:1026: in function <NameplateAuras\src\NameplateAuras.lua:1000>
[string "@NameplateAuras\src\NameplateAuras-90001.2-release.lua"]:845: in function <NameplateAuras\src\NameplateAuras.lua:818>
[string "@NameplateAuras\src\NameplateAuras-90001.2-release.lua"]:1120: in function `?'
[string "@NameplateAuras\src\NameplateAuras-90001.2-release.lua"]:1098: in function <NameplateAuras\src\NameplateAuras.lua:1098>

Locals:

and this 

26x NameplateAuras\src\NameplateAuras-90001.2-release.lua:1027: bad argument #2 to 'math_max' (number expected, got nil)
[string "=[C]"]: ?
[string "@NameplateAuras\src\NameplateAuras-90001.2-release.lua"]:1027: in function <NameplateAuras\src\NameplateAuras.lua:1000>
[string "@NameplateAuras\src\NameplateAuras-90001.2-release.lua"]:845: in function <NameplateAuras\src\NameplateAuras.lua:818>
[string "@NameplateAuras\src\NameplateAuras-90001.2-release.lua"]:1150: in function `?'
[string "@NameplateAuras\src\NameplateAuras-90001.2-release.lua"]:1098: in function <NameplateAuras\src\NameplateAuras.lua:1098>

Locals:
(*temporary) = 0
(*temporary) = nil
(*temporary) = "number expected, got nil"

 hope fix i have installe d last version..  90001.2

**Expected behavior**

**Screenshots**

**Comment by casualshammy** [comment]
Thank you for report with log! It's really helpful. I've released a fix, it will be available for download in a few minutes.
