### ISSUE TITLE
Keep ratio/Fill option for custom icon shapes

### ISSUE THREAD

**Issue by roanaes** [casualshammy/NameplateAuras#86]
First of all, great additions to features on the latest build, reall like them! However what seems to be missing is the option to keep the icon aspect ratio when you use custom icon height and width. 

I'm wishing it would be possible to keep the aspect ratio of the icon so you can achieve similiar icons to what default ui brings. 

Otherwise loving the new features and your addon and really appreciate it!

**Comment by casualshammy** [comment]
Hello.
> option to keep the icon aspect ratio when you use custom icon height and width

I don't clearly understand what do you mean. You are free to set icon's default width and height, also you can set these values on per-aura basis.

**Comment by roanaes** [comment]
I will attach screenshot shortly (around 5min)

**Comment by roanaes** [comment]
So here is how it looks with nameplate auras when using rectangle shape for me. (The icon aspect ratio breaks)
![nauras3](https://user-images.githubusercontent.com/26468754/96713087-bd855f00-13a8-11eb-8f7c-1c8b6fcd0cd9.jpg)

Here is how it looks with default ui with rectangle shape, little hard to see, but the icons get zoomed in and the aspect ratio is kept.
![nauras4](https://user-images.githubusercontent.com/26468754/96713091-be1df580-13a8-11eb-8b09-5d71bc2e98da.jpg)

**Comment by casualshammy** [comment]
Ah, it's smth like image cropping. Understood. I'll look into it.

**Comment by roanaes** [comment]
> Ah, it's smth like image cropping. Understood. I'll look into it.

Cool! Also tbh I'm not sure how blizzard does it in its ui, but weakauras is also able to do this, here's screenshot from weakauras. Maybe it will be helpful. Again thanks for this awesome addon! Do you have paypal or smth for donations?
![nauras5](https://user-images.githubusercontent.com/26468754/96714625-181fba80-13ab-11eb-987a-a2c7204eab78.jpg)

**Comment by roanaes** [comment]
Also tbf it looks quite decent even without that option once I managed to adjust the settings bit more, but perhaps it's still worth looking into this feature? Here's image how it looks now, I'm quite pleased indeed!
![nauras6](https://user-images.githubusercontent.com/26468754/96716231-6e8df880-13ad-11eb-95ad-f5ec0c97a6e2.jpg)

**Comment by casualshammy** [comment]
I will appreciate if you'll find spare time to try out the latest beta (you can install it via Twitch client or download [directly](https://www.curseforge.com/wow/addons/nameplateauras/download/3088699)).
> Cool! Also tbh I'm not sure how blizzard does it in its ui, but weakauras is also able to do this, here's screenshot from weakauras. Maybe it will be helpful. 

Thank you, it was interesting.
> Do you have paypal or smth for donations?

There is 'Sponsor' link on the top of this page.

**Comment by roanaes** [comment]
> I will appreciate if you'll find spare time to try out the latest beta (you can install it via Twitch client or download [directly](https://www.curseforge.com/wow/addons/nameplateauras/download/3088699)).
> 
It seems to be working exactly like I wished and I didn't notice any issues so far in the short time I tested it. I'm very happy with it atm!! Thank you very much :D


> 
> There is 'Sponsor' link on the top of this page.
I'll add a small tip, really liking this addon right now, almost everything I could wish for!!
