### ISSUE TITLE
Unable to hide Built-in borders

### ISSUE THREAD

**Issue by roanaes** [casualshammy/NameplateAuras#87]
Unable to hide Built-in borders. If I recall correctly you used to have just clean icons without any borders or anything extra when you disabled borders in settings, now it seems you are unable to hide the built-in icon borders.

**Screenshots**
![nauras](https://user-images.githubusercontent.com/26468754/96707716-e7d31e80-13a0-11eb-8fcf-3ce8577b506e.png)

**Comment by roanaes** [comment]
Here is how it used to look when borders were disabled. If this feature will be fixed/brought back and you will be able to keep icon aspect ratio with custom sizes this addon will be 6/5 for me personally :D love it already though!

![nauras2](https://user-images.githubusercontent.com/26468754/96708284-af801000-13a1-11eb-9409-74be733c52b2.jpg)

**Comment by casualshammy** [comment]
Hello.
Please check the 'Zoom' value. Is it equal to zero?
![Image](https://user-images.githubusercontent.com/4965168/96709115-231a2100-1392-11eb-8bf9-4dcf34bbc276.png)

**Comment by roanaes** [comment]
*facepalm* yes... it was 0 and I see now why you asked... so raising zoom fixed it :D sorry for wasting your time!
