### ISSUE TITLE
Can't seem to filter out Rampant Growth, Reactive Resin

### ISSUE THREAD

**Issue by nedempst** [casualshammy/NameplateAuras#88]
**Describe the bug**
I go into the spells section and load up Reactive Resin, Focused Growth, spells that I don't really want to see on the NP and when disable all of it, it still seems to show up on the name plate.

**To Reproduce**
1. Load up the UI
2. Search for Reactive Resin, Focused Growth
3. Uncheck all the boxes
4. Close

**Expected behavior**
When you cast hots these residual effects will not show up also

**Screenshots**
Attached screenshot tried it all with spell ID from wowhead, but it's not recognizing it for some reason. Same with Rampant Growth.
![image](https://user-images.githubusercontent.com/59960468/96946532-386a8900-1513-11eb-9e43-85ad885a581b.png)

**Comment by casualshammy** [comment]
Hello,
Maybe you have enabled `Always show auras cast by myself` option in the `General` section of the options window?

**Comment by nedempst** [comment]
I did you close the ticket sorry started working after thanks

**Comment by nedempst** [comment]
Hi there is it possible to set up a profile per spec? Like for my MW i 
want to have his hots show up but not if I am in WW mode. (At least not 
on allies plates)


------ Original Message ------
From: "Neil D" <nedempst@gmail.com>
To: "casualshammy/NameplateAuras" 
<reply@reply.github.com>
Cc: "casualshammy/NameplateAuras" <NameplateAuras@noreply.github.com>; 
"Author" <author@noreply.github.com>
Sent: 23/10/2020 4:08:34 PM
Subject: Re: [casualshammy/NameplateAuras] Can't seem to filter out 
Rampant Growth, Reactive Resin (#88)
