### ISSUE TITLE
change the icon size of crowd control

### ISSUE THREAD

**Issue by Jopla0491** [casualshammy/NameplateAuras#89]
Hi there,
Is there a way to change the icon size of important abilities (pvp) and cc just like flyplatebuffs does? 
ex. my roots, cyclone, vortex, ...all have the same icon size then my dots. It is hard to determine wich mob has cc.
Thanks!

**Comment by casualshammy** [comment]
Hi,
Erm... You can set the icon size on per-spell basis. There is no groups like 'cc' or 'pvp'.
