### ISSUE TITLE
Missing spells

### ISSUE THREAD

**Issue by antarek** [casualshammy/NameplateAuras#90]
I haven't been able to find a way to disable specific auras displayed by NameplateAuras on my Affliction Warlock.

For instance Drain Soul is displayed over my target nameplate but i d rather like not to have it displayed. So i searched among all spells listed in the 'Spells' part of the configuration menu but Drain Soul (198590) wasn't listed. I was quite surprised to notice it so i searched for most of my Affliction Warlock offensive spells and many weren't listed such as (Agony (980), Corruption (172), Haunt (48181), Seed of Corruption (27243), Vile Taint (278350) for exemple.

All of those spells are displayed once placed on the target but there is no way to disable them for the moment.

So i d sudgest to add those spells to the spell list to let people have the choice of either turning their display ON or OFF on nameplates.

**Comment by casualshammy** [comment]
Hello,
Maybe you have enabled `Always show auras cast by myself` option in the `General` section of the options window?

**Comment by antarek** [comment]
> Hello,
> Maybe you have enabled `Always show auras cast by myself` option in the `General` section of the options window?

Exact. I had to manually add the missing spells but the end result is that this is now working as expected. One exception though, Corruption (172) isn't displayed. I ve set it to only be displayed if cast by me and on enemy nameplates. I didn't activated neither the glow or animated options for it.

Thanks for the help.

**Comment by casualshammy** [comment]
> Agony stacks aren't displayed

Unfortunately, I don't have warlock to test this spell... If I remember correctly, there was problem with stacks of `Agony` from the very beginning of development. I'll look into this, if I'll find time to create and level up warlock.

> One potentialy confusing issue though: for the Corruption spell that is tagged as having 172 as its spell ID on my actionbar, entering this number into the spell ID check area ll prevent it from being displayed because of Corruption using a different ID than the one listed on my actionbar when displayed on the enemy nameplate. So to have it displayed i have to let the spell ID check area empty.

Looks like spell id of your spell and spell id of aura it applies is different. It happens. NameplateAuras assumes that, if you enter spell id instead of spell name, you know what you are doing :)

**Comment by casualshammy** [comment]
I have found lvl.10 warlock. Agony stacks are correctly displayed:
![1](https://user-images.githubusercontent.com/4965168/97301708-04170580-1850-11eb-9e40-a730d40ad6b4.jpg)

**Comment by antarek** [comment]
> I have found lvl.10 warlock. Agony stacks are correctly displayed:
> ![1](https://user-images.githubusercontent.com/4965168/97301708-04170580-1850-11eb-9e40-a730d40ad6b4.jpg)

Exact. I noticed it after increasing the default icon size. I didn't saw it prior to it so my bad.

Once again, thanks for the help casualshammy 👍.
