### ISSUE TITLE
Auras on friendly nameplates in dungeon

### ISSUE THREAD

**Issue by Asofh** [casualshammy/NameplateAuras#91]
Hello, im asking here because i dont know if it is intended to work like this or simply a bug. I have selected the option to show auras on friendly nameplates plus the option to show only my auras and this works in open world but when i enter a dungeon i cannot see any of my buff on friendly nameplates. Thx for the help

**Comment by casualshammy** [comment]
Hello,
It's intended by Blizzard. Please read: https://www.wowhead.com/news=260801/addons-friendly-nameplates-in-patch-7-2

**Comment by Asofh** [comment]
oh damn, i wasnt aware of this. Well thx for the answer.

**Comment by ScottIngram** [comment]
Thanks for the answer.  I bet a tooltip or note of some sort in the addon itself would prevent people like me coming here and pestering you for the same answer again and again.
