### ISSUE TITLE
Show only on target.

### ISSUE THREAD

**Issue by Dominik723** [casualshammy/NameplateAuras#92]
Hello there.
1. Can you able to add function “Show the auras on the current target nameplates only“ ?
2. Show auras only own choice ?
3. Hide pernamently auras ?

It would by good for overview on battlefield.

Thank you and have nice days.

**Comment by casualshammy** [comment]
Hello,
> Show auras only own choice ?

Sorry, I don't understand. You can add/remove any spell you want.
> Hide pernamently auras ?

Why you don't want to just delete permanent auras from the list of auras?

**Comment by Dominik723** [comment]
Ah, sorry my bad. I didn't notice. But It still not working. [https://ibb.co/fp5Y78Q](url)

**Comment by casualshammy** [comment]
Maybe you have enabled `Always show auras cast by myself` option in the General section of the options window?

**Comment by Dominik723** [comment]
Yeah, I have enabled, but I need any of auras show cast by myself.

**Comment by casualshammy** [comment]
Sorry, it's impossible. There is not "blacklist inside whitelist" or something like this. In your case, I suggest to disable `Always show auras cast by myself` option and add all your spells you want to see.

**Comment by Dominik723** [comment]
Ou, thank you very much for your aid.

**Comment by casualshammy** [comment]
TODO: display auras only on target

**Comment by casualshammy** [comment]
Fixed in 90002.0-release.
