### ISSUE TITLE
Frame Strata Issue

### ISSUE THREAD

**Issue by Bibimbapi** [casualshammy/NameplateAuras#95]
Hi!

when i have an aura on mobA and mobB is inbetween mobA and my character, then the aura on mobA clips over the nameplate of mobB. I can't seem to fix this with the frame strata options in the settings. even choosing Background will still make the aura clip over nameplates that are closer to you. would be amazing if it was possible to have the auras inherit their frame strata from their respective nameplate. 

cheers and thank you for an amazing addon!

**Comment by casualshammy** [comment]
Hi!

Technically speaking, nameplates are assigned to `WORLD` frame stata; it's lower than `BACKGROUND` (unfortunately, addons can't use the `WORLD` strata). So we cannot place auras behind nameplates if we use Blizzard nameplates. If we use third-party nameplates there is a problem: if auras inherit frame strata from nameplate, aura's frame strata cannot be changed, as mentioned [here](https://github.com/casualshammy/NameplateAuras/issues/65#issuecomment-692726657). You will get desired behavior, but there are people who would like to see auras in front of nameplates...

**Comment by Bibimbapi** [comment]
what do i do to get the desired behavior? is there something in the code I can change? cheers and thank you for the reply!

**Comment by Bibimbapi** [comment]
it seems I have to remove something you added in September. if you could message me the file and paragraph to delete, I'd be very grateful!

**Comment by casualshammy** [comment]
Version `80300.16-release` may help. But I don't know if it will work in Shadowlands.
Current version can't be 'fixed' by changing a line of code. Addon suppose that aura frame is **not** a child of nameplate, so a number of size, position and visual features will fail if you just change the parent of aura frames.

**Comment by Bibimbapi** [comment]
thank you man. I respect you so much for helping out random people on the internet. you are a really cool guy.

**Comment by casualshammy** [comment]
Random people from the internet are always welcome :) I'm sorry I can't implement your request, but I just don't ready to write a big amount of code just to cover frame behavior in two ways.
