### ISSUE TITLE
Sorting problems

### ISSUE THREAD

**Issue by nauras7777** [casualshammy/NameplateAuras#96]
1. Currently "By icon size" type sorting arrangement shows small icon first, but I want a big icon to be displayed first.

2. In addition to the first suggestion, like "By aura type + by expiration time" sorting, I want a "By icon size + by expiration time" type sorting. 

I like your addon very much. It would be great if my suggestion could be reflected.

**Comment by casualshammy** [comment]
> Currently "By icon size" type sorting arrangement shows small icon first, but I want a big icon to be displayed first.

Set `Icon growing direction` option.

> In addition to the first suggestion, like "By aura type + by expiration time" sorting, I want a "By icon size + by expiration time" type sorting.

Use custom sorting function. [Here](https://github.com/casualshammy/NameplateAuras/issues/76) you can see how to find this option.
Your code (from lesser amount of remaining time / small icon size -->> bigger amount of remaining time / bigger icon size). If you are not familiar with lua scripting, feel free to ask to adjust this script to your needs.
``` lua
function(aura1, aura2) 
    local sortBySizeA = sort_size(aura1, aura2);
    local sortBySizeB = sort_size(aura2, aura1);
    if (sortBySizeA == sortBySizeB) then
        return sort_time(aura1, aura2);
    else
        return sortBySizeA;
    end
end
```

**Comment by nauras7777** [comment]
Thank you for your kind reply. Thanks to you, I've got it.
