### ISSUE TITLE
Icon priority system

### ISSUE THREAD

**Issue by presnetjay** [casualshammy/NameplateAuras#98]
I can't understand Icon priority systems. I tried lots of lua scripts, but can't solve the problem.

I'm playing feral druid now, I want to sort debuffs 1. Rake / 2. Rip / 3. Thrash,

Can anyone tell me lua script for this sorting?

**Comment by casualshammy** [comment]
Oh, I'm so sorry I haven't noticed this issue.
Script for you:
``` lua
function(aura1, aura2) return aura1.spellName < aura2.spellName; end
```
