### ISSUE TITLE
Soul rot not tracked

### ISSUE THREAD

**Issue by antarek** [casualshammy/NameplateAuras#99]
Hi,

I tried to add Soul Rot (325640), an extra ability from Shadowland, to those being tracked using NameplateAuras but it doesn't work as far as nothing is displayed after using this skill (neither its effect duration nor its icon).

Here is a screenshot of my settings for this skill:

https://i.ibb.co/gzvkd7k/soul-rot-bug.jpg

**Comment by casualshammy** [comment]
I have not high-level warlock to test this spell, but... what if you delete spell id check?
